# scripts/gen_mba8109.py
# 166 High-Yield MBA Questions for MBA 8109: General Management

def get_questions():
    course_code = "MBA 8109"
    course_title = "General Management"
    q_data = []

    raw = [
        # --- TOPIC 1: EVOLUTION OF MANAGEMENT THOUGHT (1-30) ---
        ("Evolution of Management Thought",
         "Who is widely recognized as the 'Father of Scientific Management' for his pioneering work on time-and-motion studies, standardization, and task specialization?",
         ["Henri Fayol", "Frederick Winslow Taylor", "Max Weber", "Elton Mayo"],
         1,
         "Frederick Winslow Taylor developed Scientific Management (Taylorism), using empirical time-and-motion studies, task standardization, and wage incentives to maximize labor productivity."),

        ("Evolution of Management Thought",
         "Henri Fayol identified which five primary functions of management?",
         ["Planning, Organizing, Commanding, Coordinating, and Controlling (POCCC)",
          "Promoting, Advertising, Pricing, Distributing, and Selling",
          "Designing, Coding, Testing, Debugging, and Deploying",
          "Borrowing, Investing, Speculating, Auditing, and Liquidating"],
         0,
         "Henri Fayol's administrative theory outlined 5 core management functions (often modernized as POLC: Planning, Organizing, Leading, Controlling)."),

        ("Evolution of Management Thought",
         "In Fayol's 14 Principles of Management, the 'Unity of Command' principle dictates that:",
         ["An organization must have only one chief executive officer",
          "Each employee should receive orders from and be accountable to only one direct supervisor to prevent conflicting instructions",
          "All corporate departments must be located in a single physical headquarters building",
          "Employees must speak only one national language during business hours"],
         1,
         "Unity of Command ensures clarity of direction and accountability by mandating that an employee reports to only one immediate superior."),

        ("Evolution of Management Thought",
         "What is the 'Unity of Direction' principle according to Henri Fayol?",
         ["All company motor vehicles must drive in the same compass direction",
          "All activities with the same objective must be directed by one manager using one unified plan ('One head and one plan for a group of activities')",
          "Employees must live in the same geographic municipality as the corporate office",
          "Production lines must move strictly from left to right across the factory floor"],
         1,
         "Unity of Direction specifies that operations having the same strategic objective should be coordinated under a single leader and unified plan."),

        ("Evolution of Management Thought",
         "What is 'Esprit de Corps' in Fayol's management principles?",
         ["The physical health and stamina of factory workers",
          "Promoting team spirit, harmony, mutual trust, and unity among personnel to build a cohesive organizational workforce",
          "The legal corporate charter registered with government authorities",
          "A mandatory corporate dress code requiring military-style uniforms"],
         1,
         "Esprit de Corps emphasizes team harmony, morale, and unity as fundamental drivers of organizational strength and collaboration."),

        ("Evolution of Management Thought",
         "Max Weber's model of 'Bureaucracy' is fundamentally characterized by:",
         ["Nepotism, casual verbal agreements, and emotional decision-making",
          "Clear jurisdictional hierarchy, formal written rules, division of labor, impersonality, and merit-based career advancement",
          "Flat autonomous self-managing holacracies with zero managers",
          "Temporary short-term freelance contracts with zero job security"],
         1,
         "Weberian Bureaucracy provides rational-legal order: clear authority hierarchy, formal operating rules, documented records, impersonality, and meritocracy."),

        ("Evolution of Management Thought",
         "The landmark 'Hawthorne Studies' conducted by Elton Mayo and Fritz Roethlisberger at Western Electric revealed that:",
         ["Worker productivity is strictly determined by physical lighting levels and room temperature",
          "Social relations, group norms, managerial attention, and psychological factors significantly influence workplace productivity and morale ('Hawthorne Effect')",
          "Financial wage incentives are the only motivator workers care about",
          "Automated assembly lines completely eliminate the need for human supervision"],
         1,
         "The Hawthorne Studies catalyzed the Human Relations Movement by proving that workers are social beings influenced by group dynamics, recognition, and attention."),

        ("Evolution of Management Thought",
         "What is the 'Systems Approach' to management?",
         ["Viewing the organization as a collection of completely isolated, unrelated departments",
          "Viewing the organization as an interconnected, unified whole comprised of interrelated subsystems (inputs, transformation processes, outputs, feedback) interacting with the external environment",
          "Replacing human managers with automated mainframe computing scripts",
          "Operating a business strictly using mechanical calculating machinery"],
         1,
         "The Systems Approach conceptualizes organizations as open socio-technical systems that transform environmental inputs into outputs while adapting to feedback."),

        ("Evolution of Management Thought",
         "What is the core premise of the 'Contingency (Situational) Approach' to management?",
         ["There is one universally best management practice that works identically in all situations ('One Best Way')",
          "There is no single best way to manage; managerial actions and organizational structures must be tailored to the specific contingencies of the situation, environment, technology, and people",
          "All corporate managers must hold identical academic degrees",
          "Managers should flip a coin to make daily operating decisions"],
         1,
         "Contingency theory ('it depends') asserts that optimal leadership, organizational design, and strategy depend on specific internal and external situational variables."),

        ("Evolution of Management Thought",
         "In the Systems Approach, the concept of 'Equifinality' means:",
         ["All employees must receive identical salaries regardless of seniority",
          "An organization can reach the same final goal or desired end-state through multiple different paths, strategies, and initial conditions",
          "All business ventures eventually terminate in bankruptcy after twenty years",
          "Equal numbers of male and female directors must sit on the board"],
         1,
         "Equifinality in open systems demonstrates that there is no singular path to success; different strategic routes can achieve the same organizational objectives."),

        # --- TOPIC 2: MANAGERIAL ROLES & FUNCTIONS (31-65) ---
        ("Managerial Roles & Functions",
         "According to Henry Mintzberg's Managerial Roles framework, the ten roles are grouped into which three broad categories?",
         ["Interpersonal, Informational, and Decisional",
          "Financial, Operational, and Tactical",
          "Administrative, Legal, and Strategic",
          "Technical, Clerical, and Executive"],
         0,
         "Mintzberg categorized managerial activity into Interpersonal (Figurehead, Leader, Liaison), Informational (Monitor, Disseminator, Spokesperson), and Decisional (Entrepreneur, Disturbance Handler, Resource Allocator, Negotiator)."),

        ("Managerial Roles & Functions",
         "In Mintzberg's typology, which role involves transmitting information gathered from outside or from subordinates to other members of the organization?",
         ["Disseminator Role", "Figurehead Role", "Resource Allocator Role", "Disturbance Handler Role"],
         0,
         "As a Disseminator (Informational category), a manager distributes valuable information, strategic updates, and data internally across the team."),

        ("Managerial Roles & Functions",
         "When a CEO attends a formal ribbon-cutting ceremony for a new regional hospital or hosts visiting foreign dignitaries, they are performing which Mintzberg role?",
         ["Figurehead Role", "Negotiator Role", "Monitor Role", "Resource Allocator Role"],
         0,
         "The Figurehead role (Interpersonal category) encompasses ceremonial, symbolic, and legal duties required of organizational leaders."),

        ("Managerial Roles & Functions",
         "According to Robert L. Katz, what three essential managerial skills are required across different levels of management?",
         ["Technical Skills, Human (Interpersonal) Skills, and Conceptual Skills",
          "Physical Skills, Linguistic Skills, and Artistic Skills",
          "Accounting Skills, Legal Skills, and Advertising Skills",
          "Typing Skills, Driving Skills, and Public Speaking Skills"],
         0,
         "Katz established that managers need Technical skills (specialized methods), Human skills (working with people), and Conceptual skills (holistic strategic vision)."),

        ("Managerial Roles & Functions",
         "According to Katz's model, as a manager climbs from first-line supervision to top executive leadership, the relative importance of which skill increases the most?",
         ["Technical Skills", "Conceptual Skills", "Physical Stamina", "Micro-Detail Auditing"],
         1,
         "Top executives primarily require high Conceptual skills to analyze complex systemic dynamics, formulate strategy, and understand holistic interdependencies."),

        ("Managerial Roles & Functions",
         "What is 'Span of Control' in organizational design?",
         ["The total physical length of an assembly factory floor",
          "The number of direct subordinates or employees who report directly to a single manager or supervisor",
          "The maximum distance a corporate delivery truck can travel in a day",
          "The time duration of an executive board meeting"],
         1,
         "Span of control measures how many direct reports a manager oversees. Narrow spans create tall hierarchies; wide spans create flat organizational structures."),

        ("Managerial Roles & Functions",
         "What is the difference between a 'Tall' and 'Flat' organizational structure?",
         ["Tall structures have many hierarchical management levels with narrow spans of control; Flat structures have few management levels with wide spans of control",
          "Tall structures are built in skyscraper towers; Flat structures are built on farmland",
          "Tall structures have no managers; Flat structures have dozens of CEOs",
          "Tall structures operate without rules; Flat structures have strict government supervision"],
         0,
         "Tall structures have multiple hierarchical layers and narrow spans (more oversight, slower communication); flat structures have few layers and wide spans (faster decisions, empowerment)."),

        ("Managerial Roles & Functions",
         "What is 'Centralization' versus 'Decentralization' in decision-making authority?",
         ["Centralization concentrates decision-making authority at top executive levels; Decentralization disperses authority down to lower operational levels and front-line managers",
          "Centralization moves offices to capital cities; Decentralization moves offices to rural villages",
          "Centralization uses only paper files; Decentralization uses cloud databases",
          "Centralization occurs exclusively in non-profit charities"],
         0,
         "Centralization concentrates authority at the strategic apex; decentralization empowers lower-level managers, improving local responsiveness and employee autonomy."),

        ("Managerial Roles & Functions",
         "In a 'Matrix Organizational Structure', what structural feature violates the traditional Unity of Command principle?",
         ["Employees reporting simultaneously to two bosses: a functional department manager and a product/project manager",
          "Employees having no supervisors whatsoever",
          "Every employee being appointed to the corporate board of directors",
          "Employees working exclusively from home on weekends"],
         0,
         "Matrix structures utilize a dual-reporting chain of command (functional vertical + project horizontal), balancing technical depth with project focus at the cost of potential role conflict."),

        ("Managerial Roles & Functions",
         "What is the difference between 'Line Authority' and 'Staff Authority' in organizations?",
         ["Line managers have direct authority to make decisions and direct subordinates in core value-generating operations; Staff managers provide specialized advisory, consulting, and support services to line managers",
          "Line managers draw straight lines on blueprints; Staff managers write musical compositions",
          "Line managers work only part-time; Staff managers work full-time",
          "Line managers have zero authority over any employees"],
         0,
         "Line authority flows directly along the chain of command (e.g., Plant Manager, Sales Director); Staff authority is advisory/support (e.g., Legal, HR, Strategic Planning)."),

        ("Managerial Roles & Functions",
         "What are the four sequential steps in the standard Managerial Control Process?",
         ["1. Establish performance standards; 2. Measure actual performance; 3. Compare actual performance against standards; 4. Take corrective action if necessary",
          "1. Hire workers; 2. Pay wages; 3. Issue penalties; 4. Liquidate assets",
          "1. Write software; 2. Launch product; 3. Count revenue; 4. Celebrate success",
          "1. Borrow capital; 2. Purchase machines; 3. Rent office; 4. File taxes"],
         0,
         "The universal control process: Set Standards $\rightarrow$ Measure Performance $\rightarrow$ Compare with Standards (variance analysis) $\rightarrow$ Take Corrective Action."),

        ("Managerial Roles & Functions",
         "What is 'Feedforward Control' (Preliminary Control)?",
         ["A control mechanism that occurs during the actual execution of an activity",
          "A proactive control mechanism implemented before an activity begins to anticipate and prevent problems and ensure input resources meet required specifications",
          "A post-mortem performance appraisal conducted after project completion",
          "A daily financial audit of retail cash registers at closing time"],
         1,
         "Feedforward control anticipates and prevents deviations before they occur by screening inputs and establishing rigorous preventative standards (e.g., pre-employment drug tests, raw material specs)."),

        ("Managerial Roles & Functions",
         "What is 'Concurrent Control' (Steering Control)?",
         ["Control exercised while an operational activity or process is actively taking place, allowing immediate on-the-spot adjustments (e.g., direct supervision, live sensor monitoring)",
          "Control conducted five years after a product is retired",
          "A meeting between two competing CEOs to fix prices",
          "An audit of historical financial statements from the prior decade"],
         0,
         "Concurrent control monitors and adjusts ongoing operations in real-time (e.g., factory quality checkpoints, real-time server traffic routing)."),

        ("Managerial Roles & Functions",
         "What is 'Feedback Control' (Post-Action Control)?",
         ["Control implemented after an operational activity or process has concluded, evaluating historical results against targets (e.g., quarterly financial reports, customer satisfaction surveys)",
          "Preventative maintenance performed before installing machinery",
          "A real-time dashboard alert signaling high temperature",
          "A casual hallway conversation between colleagues"],
         0,
         "Feedback control evaluates finished performance outputs against benchmarks to assess variance, allocate rewards, and inform future planning cycles."),

        ("Managerial Roles & Functions",
         "The 'Balanced Scorecard' framework developed by Robert Kaplan and David Norton measures organizational performance across which four perspectives?",
         ["Financial, Customer, Internal Business Processes, and Learning & Growth",
          "Accounting, Marketing, Human Resources, and Legal",
          "Production, Logistics, Packaging, and Distribution",
          "Assets, Liabilities, Equity, and Retained Earnings"],
         0,
         "The Balanced Scorecard balances lagging financial indicators with leading operational drivers across 4 perspectives: Financial, Customer, Internal Processes, and Learning/Growth."),

        # --- TOPIC 3: STRATEGIC MANAGEMENT & COMPETITIVE FRAMEWORKS (66-105) ---
        ("Strategic Management & Frameworks",
         "What is the difference between an organization's 'Vision Statement' and 'Mission Statement'?",
         ["A Vision statement articulates what the organization aspires to become in the future; a Mission statement defines its core purpose, what it does, who it serves, and why it exists today",
          "A Vision statement is written for government tax agencies; a Mission statement is for employees",
          "There is zero difference; they are identical legal terms",
          "A Vision statement specifies quarterly profit margins; a Mission statement lists office rules"],
         0,
         "A Mission defines the present business purpose, value proposition, and customer focus; a Vision paints an inspiring picture of long-term aspirational future impact."),

        ("Strategic Management & Frameworks",
         "What are Michael Porter's three Generic Strategies for achieving competitive advantage?",
         ["Cost Leadership, Differentiation, and Focus (Cost Focus or Differentiation Focus)",
          "Monopolization, Cartelization, and Nationalization",
          "Low Quality, High Price, and Aggressive Advertising",
          "Exporting, Licensing, and Franchising"],
         0,
         "Porter's Generic Strategies identify fundamentally distinct routes to above-average industry returns: broad Cost Leadership, broad Differentiation, or niche Focus."),

        ("Strategic Management & Frameworks",
         "What occurs when an organization is 'Stuck in the Middle' according to Michael Porter?",
         ["It achieves the highest profit margins in its industry",
          "It fails to develop a clear competitive advantage, attempting to pursue both low cost and differentiation simultaneously without excellence in either, resulting in below-average profitability",
          "Its physical office is located between two competing retail stores",
          "It has an equal number of male and female executive managers"],
         1,
         "A firm stuck in the middle lacks the scale/efficiency of cost leaders and the unique premium appeal of differentiators, resulting in weak competitive positioning and poor margins."),

        ("Strategic Management & Frameworks",
         "In the BCG (Boston Consulting Group) Growth-Share Matrix, a business unit with 'High Market Growth Rate and High Relative Market Share' is categorized as a:",
         ["Cash Cow", "Star", "Question Mark (Problem Child)", "Dog"],
         1,
         "Stars have high market share in high-growth industries; they generate strong revenues but require significant ongoing capital investment to maintain market leadership."),

        ("Strategic Management & Frameworks",
         "In the BCG Matrix, what is a 'Cash Cow'?",
         ["A dairy farm operated by agricultural conglomerates",
          "A business unit with High Relative Market Share in a Low-Growth (mature) industry, generating high cash surpluses with minimal required reinvestment",
          "A loss-making business unit that consumes all corporate cash reserves",
          "A brand-new speculative product launched last week"],
         1,
         "Cash Cows dominate mature, slow-growth markets, throwing off substantial excess cash flow that the parent corporation can harvest to fund Stars and Question Marks."),

        ("Strategic Management & Frameworks",
         "In the BCG Matrix, what is a 'Dog'?",
         ["A corporate guard animal trained for warehouse security",
          "A business unit with Low Relative Market Share in a Low-Growth market, generating little or negative cash flow and typically prime for divestment or liquidation",
          "A fast-growing speculative technology venture",
          "A company that spends 50% of its budget on television commercials"],
         1,
         "Dogs occupy weak positions in stagnant industries; they generate low returns, consume managerial time, and are typical candidates for harvest, sale, or shutdown."),

        ("Strategic Management & Frameworks",
         "The 'Ansoff Matrix' classifies corporate growth strategies into four distinct quadrants based on combinations of:",
         ["Existing vs. New Products and Existing vs. New Markets (Market Penetration, Market Development, Product Development, Diversification)",
          "High vs. Low Price and High vs. Low Cost",
          "Domestic vs. International Taxes and Equity vs. Debt",
          "Male vs. Female Employees and Young vs. Old Customers"],
         0,
         "The Ansoff Product-Market Grid maps growth options: Market Penetration (existing/existing), Market Development (new markets/existing products), Product Development (new products/existing markets), and Diversification (new/new)."),

        ("Strategic Management & Frameworks",
         "In the Ansoff Matrix, which growth strategy involves selling existing products to new geographic regions or new customer demographic segments?",
         ["Market Penetration", "Market Development", "Product Development", "Diversification"],
         1,
         "Market Development takes established products into unserved geographic markets, international territories, or new demographic customer segments."),

        ("Strategic Management & Frameworks",
         "Which Ansoff growth strategy carries the highest operational and strategic risk?",
         ["Market Penetration", "Product Development", "Market Development", "Diversification (especially Unrelated Diversification)"],
         3,
         "Diversification carries the highest risk because the firm simultaneously enters unfamiliar product development and uncharted customer market territories."),

        ("Strategic Management & Frameworks",
         "In the Resource-Based View (RBV) of the firm, the 'VRIO Framework' (Jay Barney) evaluates resources across which four criteria to determine sustained competitive advantage?",
         ["Value, Rarity, Inimitability, and Organization (Exploitation by Organization)",
          "Volume, Rate, Interest, and Overhead",
          "Vision, Reputation, Integrity, and Optimization",
          "Velocity, Revenue, Inventory, and Options"],
         0,
         "Under VRIO, a resource yields sustained competitive advantage only if it is Valuable, Rare, Imperfectly Imitable (costly to copy), and the firm is Organized to exploit it."),

        ("Strategic Management & Frameworks",
         "What is 'Value Chain Analysis' introduced by Michael Porter?",
         ["An audit of physical jewelry and gold assets in company vaults",
          "A systematic framework dividing a firm's activities into Primary Activities (Inbound Logistics, Operations, Outbound Logistics, Marketing/Sales, Service) and Support Activities (Procurement, HR, Tech, Infrastructure) to identify sources of cost advantage or differentiation",
          "A supply chain flowchart tracking maritime cargo vessels",
          "A performance evaluation rubric used by HR departments"],
         1,
         "Porter's Value Chain decomposes operations into 5 Primary and 4 Support activities, analyzing how each links together to deliver margin and competitive value."),

        ("Strategic Management & Frameworks",
         "What is 'Core Competence' as defined by C.K. Prahalad and Gary Hamel?",
         ["The minimum basic skill required to complete an entry-level job application",
          "A harmonized combination of multiple resources, technologies, and skills that distinguish a firm competitively, provide access to a wide variety of markets, and are difficult for rivals to imitate",
          "The legal authority of the chief executive officer to sign contracts",
          "The standard operating procedures printed in the employee handbook"],
         1,
         "Core competencies (e.g., Honda's engine design, Canon's optics) are deep cross-functional capabilities that underpin multiple product lines and power competitive advantage."),

        # --- TOPIC 4: MANAGERIAL DECISION MAKING & COGNITIVE BIASES (106-135) ---
        ("Decision Making & Biases",
         "Herbert Simon was awarded the Nobel Prize for introducing the concept of 'Bounded Rationality', which posits that:",
         ["Human decision-makers possess infinite computational capacity and always choose the mathematically optimal decision",
          "Human decision-makers face cognitive limitations, information constraints, and time limits, leading them to 'Satisfice' (choose satisfactory, good-enough solutions) rather than optimize",
          "Corporate managers should make all strategic decisions by rolling dice",
          "Rational decisions are strictly illegal under international corporate jurisprudence"],
         1,
         "Bounded Rationality recognizes that human cognitive bandwidth, incomplete information, and time pressures prevent pure optimization, resulting in 'satisficing' behavior."),

        ("Decision Making & Biases",
         "What is 'Satisficing' in managerial decision-making?",
         ["Conducting customer satisfaction surveys after each transaction",
          "Searching through available alternatives only until an option that meets an acceptable minimum threshold or aspiration level is found, rather than exhausting all options to find the absolute optimum",
          "Fulfilling all shareholder dividend demands with zero retained earnings",
          "Achieving 100% mathematical perfection on accounting ledgers"],
         1,
         "Satisficing (satisfy + suffice) is selecting the first alternative that meets acceptable criteria rather than conducting exhaustive searches for the theoretically optimal solution."),

        ("Decision Making & Biases",
         "What is the 'Anchoring and Adjustment Bias'?",
         ["The practice of securing maritime freight ships with steel anchor cables",
          "A cognitive bias where an individual relies too heavily on an initial piece of information (the 'anchor') when making subsequent estimates or decisions, failing to adjust sufficiently",
          "A tendency to keep physical office desks in fixed, anchored floor positions",
          "A management policy that fixes employee wages permanently for ten years"],
         1,
         "Anchoring occurs when an initial number (e.g., an opening negotiation price, historical budget) disproportionately biases subsequent judgments and adjustments."),

        ("Decision Making & Biases",
         "What is the 'Sunk Cost Fallacy' (or Escalation of Commitment)?",
         ["When a cargo ship sinks and insurance claims are paid",
          "The tendency for decision-makers to continue investing additional time, money, and resources into a failing project simply because of the substantial, non-recoverable past investments already made",
          "A financial calculation of factory depreciation",
          "Liquidating an unprofitable business within twenty-four hours of inception"],
         1,
         "The Sunk Cost Fallacy ('throwing good money after bad') occurs when managers irrationally commit further resources to failing ventures to justify past unrecoverable investments."),

        ("Decision Making & Biases",
         "What is the 'Availability Heuristic' in managerial risk assessment?",
         ["Checking whether office meeting rooms are available on digital calendars",
          "The mental shortcut where people assess the probability or frequency of an event based on how easily concrete examples or instances of it come to mind",
          "A legal rule requiring retail stores to keep products in stock",
          "Evaluating whether an employee is available for weekend overtime"],
         1,
         "The Availability Heuristic overweights vivid, dramatic, or recent events (e.g., recent plane crashes, market crashes) when assessing risk probabilities."),

        ("Decision Making & Biases",
         "What is 'Framing Effect' in decision-making psychology (Tversky & Kahneman)?",
         ["Constructing wooden picture frames for corporate award certificates",
          "The cognitive bias where people draw different conclusions and make different choices based on how information or choices are presented (e.g., 90% survival rate vs. 10% mortality rate)",
          "An architectural blueprint for constructing factory walls",
          "A legal maneuver to falsely accuse an executive of corporate misconduct"],
         1,
         "Framing demonstrates that presenting identical objective outcomes through positive (gain) vs. negative (loss) lenses fundamentally alters risk preferences and choices."),

        ("Decision Making & Biases",
         "What is the difference between 'Programmed Decisions' and 'Non-Programmed Decisions'?",
         ["Programmed decisions are repetitive, routine, and handled via established rules/SOPs; Non-programmed decisions are novel, unstructured, complex, and require bespoke judgment and strategic analysis",
          "Programmed decisions are written in Python; Non-programmed are written in C++",
          "Programmed decisions are made by interns; Non-programmed are made by computers",
          "Programmed decisions take five years to execute; Non-programmed take one minute"],
         0,
         "Programmed decisions follow standard operating procedures for routine scenarios; non-programmed decisions address novel, high-stakes, ambiguous strategic situations."),

        # --- TOPIC 5: QUALITY MANAGEMENT, TQM & BENCHMARKING (136-166) ---
        ("Quality Management & Operations",
         "The 'PDCA Cycle' (Deming Wheel) of continuous quality improvement consists of which four iterative steps?",
         ["Plan, Do, Check, and Act",
          "Prepare, Deliver, Close, and Audit",
          "Promote, Discount, Calculate, and Advertise",
          "Pitch, Develop, Code, and Automate"],
         0,
         "The PDCA Cycle (Plan-Do-Check-Act), popularized by W. Edwards Deming, is the foundational iterative cycle for continuous quality improvement (Kaizen)."),

        ("Quality Management & Operations",
         "What is the core philosophy of 'Total Quality Management' (TQM)?",
         ["Inspecting and discarding defective products exclusively at the final shipping dock",
          "An organization-wide management approach focused on continuous quality improvement, customer satisfaction, total employee involvement, and process enhancement across all business functions",
          "Passing all quality control responsibilities to an external government inspector",
          "Automating 100% of factory production lines using industrial robotics"],
         1,
         "TQM is an enterprise-wide commitment to continuous improvement, customer-centric quality design, employee empowerment, and zero defects."),

        ("Quality Management & Operations",
         "In Six Sigma quality management, what is the maximum allowable number of defects per million opportunities (DPMO) for a process operating at 6-sigma level?",
         ["3.4 DPMO", "34 DPMO", "340 DPMO", "3,400 DPMO"],
         0,
         "A Six Sigma process achieves a statistical quality level of 99.99966% defect-free output, translating to no more than 3.4 defects per million opportunities."),

        ("Quality Management & Operations",
         "What does the acronym 'DMAIC' stand for in Six Sigma methodology?",
         ["Define, Measure, Analyze, Improve, and Control",
          "Design, Market, Acquire, Implement, and Calculate",
          "Discover, Maintain, Audit, Inspect, and Certify",
          "Develop, Manage, Allocate, Integrate, and Coordinate"],
         0,
         "DMAIC is the structured data-driven 5-phase methodology for improving existing business and manufacturing processes in Six Sigma."),

        ("Quality Management & Operations",
         "What is 'Kaizen' in Japanese management philosophy?",
         ["A sudden, disruptive corporate revolution executed overnight",
          "Continuous, incremental improvement involving every employee from top executives to shop floor workers",
          "A formal performance appraisal metric used for executive bonuses",
          "A statutory labor union established in manufacturing plants"],
         1,
         "Kaizen embodies the philosophy of relentless, small, incremental daily improvements across all workplace processes, eliminating waste (muda)."),

        ("Quality Management & Operations",
         "What is 'Benchmarking' in strategic management?",
         ["Measuring the physical dimensions of wooden park benches",
          "The systematic process of measuring and comparing an organization's business processes and performance metrics against industry best practices or best-in-class market leaders",
          "A disciplinary hearing conducted for underperforming employees",
          "An accounting method for recording long-term bank loans"],
         1,
         "Benchmarking compares internal operational metrics, cycle times, costs, and quality against top industry performers to identify performance gaps and adopt best practices."),

        ("Quality Management & Operations",
         "What is the 'Pareto Principle' (80/20 Rule) commonly applied to quality control?",
         ["80% of employees do 20% of the physical work in an organization",
          "Approximately 80% of consequences, defects, or customer complaints stem from 20% of causes or process flaws",
          "80% of corporation tax is paid by 20% of small businesses",
          "A business should maintain an 80% debt and 20% equity capital structure"],
         1,
         "The Pareto Principle shows that a vital few causes (20%) generate the overwhelming majority (80%) of quality defects, complaints, or revenues."),

        ("Quality Management & Operations",
         "What is an 'Ishikawa Diagram' (Fishbone Diagram / Cause-and-Effect Diagram)?",
         ["A biological anatomy diagram of aquatic marine life",
          "A visual brainstorming and root-cause analysis tool that categorizes potential causes of a specific problem or defect along major branches (e.g., Man, Machine, Method, Material, Measurement, Environment)",
          "A flowchart tracking the distribution of frozen seafood products",
          "A financial balance sheet summarizing annual net income"],
         1,
         "Developed by Kaoru Ishikawa, the Fishbone Diagram systematically maps root causes contributing to an operational defect or problem across standardized categories."),

        ("Quality Management & Operations",
         "What is 'Poka-Yoke' in lean operations and quality engineering?",
         ["A Japanese martial arts exercise conducted before morning shifts",
          "A 'mistake-proofing' mechanism or design feature that prevents human errors from occurring or immediately highlights them so they cannot proceed downstream (e.g., SIM card tray design)",
          "A financial derivatives contract traded in Tokyo",
          "A traditional tea ceremony hosted for corporate clients"],
         1,
         "Poka-Yoke involves fail-safe engineering designs that make it physically or procedurally impossible for an operator to make an error or assemble a part backwards.")
    ]

    for i, (topic, q, opts, ans, exp) in enumerate(raw, 1):
        q_data.append({
            "id": f"MBA8109_{i:03d}",
            "courseCode": course_code,
            "courseTitle": course_title,
            "topic": topic,
            "question": q,
            "options": opts,
            "correctAnswer": ans,
            "explanation": exp
        })

    return q_data

if __name__ == "__main__":
    qs = get_questions()
    print(f"Generated {len(qs)} questions for MBA 8109.")
