# scripts/gen_mba8105.py
# 167 High-Yield MBA Questions for MBA 8105: Management Information Systems (MIS)

def get_questions():
    course_code = "MBA 8105"
    course_title = "Management Information Systems"
    q_data = []

    raw = [
        # --- TOPIC 1: IS STRATEGY, ROLES & ORGANIZATIONAL HIERARCHY (1-25) ---
        ("IS Strategy & Hierarchy",
         "Which level of the organizational information system hierarchy primarily handles daily routine, operational transactions like sales processing and payroll?",
         ["Executive Support Systems (ESS)",
          "Decision Support Systems (DSS)",
          "Transaction Processing Systems (TPS)",
          "Management Information Systems (MIS)"],
         2,
         "Transaction Processing Systems (TPS) record and process daily routine operational transactions essential to business conduct (e.g., POS checkouts, ATM withdrawals, payroll)."),

        ("IS Strategy & Hierarchy",
         "A 'Decision Support System' (DSS) is characterized by its ability to:",
         ["Generate automated, standardized end-of-month accounting printouts",
          "Assist middle and senior managers in solving non-routine, semi-structured problems using analytical models and what-if simulations",
          "Physically control warehouse conveyor belts using mechanical relays",
          "Automate the sending of standard employee welcome emails"],
         1,
         "DSS combines data and sophisticated analytical models or data analysis tools to support semi-structured and unstructured decision-making."),

        ("IS Strategy & Hierarchy",
         "Executive Support Systems (ESS) or Executive Information Systems (EIS) are tailored specifically for top-tier executives by providing:",
         ["High-level strategic insights, drill-down capabilities, digital dashboards, and competitive intelligence with intuitive visual summaries",
          "Line-by-line coding interfaces for debugging software programs",
          "Detailed daily punch-card attendance logs for factory workers",
          "Raw SQL query editors without graphical interfaces"],
         0,
         "ESS/EIS delivers executive-level dashboards, portal views, and external macro-trend intelligence to support long-term strategic decision-making."),

        ("IS Strategy & Hierarchy",
         "In Michael Porter's Information Systems framework, how can an organization use IT to achieve 'Cost Leadership'?",
         ["By spending maximum capital on bespoke luxury hardware for every staff member",
          "By automating supply chain processes, eliminating transactional overhead, and streamlining operations to produce goods at the lowest cost",
          "By shutting down all digital systems and relying entirely on paper records",
          "By increasing the price of digital services by 50% annually"],
         1,
         "IT drives cost leadership through automated workflows, lean inventory systems (JIT), efficient logistics routing, and lower transaction costs."),

        ("IS Strategy & Hierarchy",
         "What is 'Business Process Reengineering' (BPR) as defined by Michael Hammer and James Champy?",
         ["Making minor incremental 1% improvements to existing departmental tasks",
          "The fundamental rethinking and radical redesign of core business processes to achieve dramatic improvements in critical performance measures like cost, quality, service, and speed",
          "Replacing desktop computer monitors with laptops",
          "Outsourcing the entire accounting department to unpaid interns"],
         1,
         "BPR involves radical redesign of end-to-end business processes, leveraging modern IT capabilities to eliminate non-value-adding operational steps."),

        ("IS Strategy & Hierarchy",
         "Which role in an enterprise is primarily responsible for aligning information technology strategy with overarching business goals, IT architecture, and digital transformation?",
         ["Chief Information Officer (CIO)", "Database Administrator (DBA)", "Network Technician", "Helpdesk Support Representative"],
         0,
         "The Chief Information Officer (CIO) leads enterprise-wide IT strategy, governance, technology investments, and digital business alignment."),

        ("IS Strategy & Hierarchy",
         "What is the difference between 'Data', 'Information', and 'Knowledge' in information systems theory?",
         ["Data are raw, unorganized facts; Information is data processed and structured in context; Knowledge is information combined with experience, context, and actionable insight",
          "Data is always printed on paper; Information is always on screens; Knowledge is only in libraries",
          "There is zero difference; the three terms are completely interchangeable",
          "Knowledge is raw binary bits; Data is executive wisdom"],
         0,
         "Data represents raw unprocessed facts/symbols. Processed into meaningful context, it becomes Information. When applied with human understanding and experience, it becomes Knowledge."),

        ("IS Strategy & Hierarchy",
         "What does a 'Digital Dashboard' provide to corporate managers?",
         ["A physical wooden board hanging on the office wall",
          "A real-time, visual reporting tool that displays Key Performance Indicators (KPIs), metrics, and critical data points on a single interactive screen",
          "An instrument panel installed on company motor vehicles",
          "A software interface used exclusively for writing computer code"],
         1,
         "Digital dashboards aggregate real-time enterprise metrics and KPIs, offering high-level visibility and deep drill-down analytics for decision-makers."),

        ("IS Strategy & Hierarchy",
         "In strategic IS planning, what is 'Strategic Alignment'?",
         ["Arranging office desks in a straight physical row",
          "The degree to which the information technology mission, objectives, and plans support and are supported by the business mission, objectives, and plans",
          "Purchasing computers from only one hardware vendor",
          "Synchronizing employee wristwatches at the start of each business day"],
         1,
         "Strategic alignment ensures IT strategy, infrastructure, and portfolio investments directly support the long-term strategic goals and competitive advantages of the enterprise."),

        ("IS Strategy & Hierarchy",
         "Which system is specifically designed to facilitate communication, coordination, document sharing, and collaboration among knowledge workers across an organization?",
         ["Knowledge Management System (KMS) / Enterprise Collaboration System",
          "Point-of-Sale (POS) Terminal",
          "General Ledger Cash Book",
          "Automated Teller Machine (ATM)"],
         0,
         "Knowledge Management Systems (KMS) and collaboration platforms capture, organize, and share organizational knowledge and foster team problem-solving."),

        ("IS Strategy & Hierarchy",
         "What is 'Tacit Knowledge' versus 'Explicit Knowledge' in Knowledge Management?",
         ["Tacit knowledge is intuitive, internalized know-how and expertise in people's minds; Explicit knowledge is codified, documented, and easily articulated in manuals or databases",
          "Tacit knowledge is stored on hard drives; Explicit knowledge is forgotten",
          "Tacit knowledge is illegal; Explicit knowledge is mandatory",
          "Tacit knowledge applies only to arithmetic; Explicit knowledge applies to literature"],
         0,
         "Nonaka and Takeuchi highlight that tacit knowledge (personal experience, intuition) must be externalized into explicit knowledge (documents, diagrams, manuals) to scale across firms."),

        ("IS Strategy & Hierarchy",
         "What is the 'SECI Model' in organizational knowledge creation?",
         ["Socialization, Externalization, Combination, and Internalization",
          "Storage, Extraction, Computation, and Indexing",
          "Security, Encryption, Compliance, and Inspection",
          "Sales, Expenses, Capital, and Investment"],
         0,
         "Nonaka's SECI model describes the knowledge conversion spiral: Socialization (tacit to tacit), Externalization (tacit to explicit), Combination (explicit to explicit), and Internalization (explicit to tacit)."),

        ("IS Strategy & Hierarchy",
         "In competitive information strategy, what is 'Lock-In'?",
         ["Physically locking office server rooms with padlocks",
          "Creating high switching costs for customers through proprietary data formats, ecosystems, or integrated systems, making it difficult or costly to switch to rivals",
          "Freezing employee computer keyboards after 5:00 PM",
          "Restricting internet access on factory floor terminals"],
         1,
         "Customer lock-in occurs when switching to a competitor entails high financial, operational, or learning friction (e.g., Apple ecosystem, enterprise ERP integrations)."),

        ("IS Strategy & Hierarchy",
         "What is 'Shadow IT' in corporate organizations?",
         ["IT hardware used strictly during nighttime shift rotations",
          "Information technology systems, software, cloud services, and devices used inside an organization without explicit IT department approval or oversight",
          "A backup server facility built inside an underground bomb shelter",
          "The dark mode visual interface setting on smartphone operating systems"],
         1,
         "Shadow IT refers to unapproved SaaS tools, apps, or devices deployed by business units without IT department clearance, raising security and compliance vulnerabilities."),

        ("IS Strategy & Hierarchy",
         "What is 'Total Cost of Ownership' (TCO) for IT infrastructure?",
         ["The sticker invoice price of physical computer hardware at purchase",
          "A comprehensive financial estimate that includes direct and indirect costs of acquiring, deploying, operating, maintaining, securing, and upgrading IT assets throughout their full lifecycle",
          "The monthly broadband internet subscription fee",
          "The hourly wage paid to an external IT repair contractor"],
         1,
         "TCO accounts for capital costs, software licensing, installation, user training, technical support, maintenance, downtime, and decommissioning costs over an asset's lifespan."),

        ("IS Strategy & Hierarchy",
         "What is 'IT Governance'?",
         ["A government ministry that dictates computer screen brightness levels",
          "The framework and leadership structures that ensure an organization's IT investments sustain and extend organizational strategies and objectives while managing risk (e.g., COBIT, ITIL)",
          "A union representing computer repair technicians",
          "The municipal zoning laws governing computer retail stores"],
         1,
         "IT Governance provides structural oversight, accountability, risk controls, and performance metrics to ensure IT delivers strategic value and aligns with enterprise risk tolerance."),

        ("IS Strategy & Hierarchy",
         "Which framework provides a comprehensive set of controls and best practices for Enterprise IT Governance and Management?",
         ["COBIT (Control Objectives for Information and Related Technologies)", "SWOT Matrix", "DuPont Formula", "Gantt Chart"],
         0,
         "COBIT (developed by ISACA) is the globally accepted framework for enterprise IT governance, risk management, and strategic alignment."),

        ("IS Strategy & Hierarchy",
         "What is 'ITIL' (Information Technology Infrastructure Library)?",
         ["A physical public library building containing computer science textbooks",
          "A widely accepted framework of best practices for delivering, managing, and optimizing IT Service Management (ITSM) to meet business needs",
          "A software programming language used for mainframe computers",
          "A government regulatory commission overseeing internet domain names"],
         1,
         "ITIL is the standard framework for IT service management (ITSM), covering service strategy, design, transition, operation, and continual service improvement."),

        ("IS Strategy & Hierarchy",
         "In IT portfolio management, what is the purpose of categorizing IT investments into 'Run', 'Grow', and 'Transform'?",
         ["To balance IT spending between keeping current operations running, expanding existing capabilities, and funding disruptive digital innovations",
          "To schedule physical exercise routines for software development staff",
          "To classify employee job performance into three salary grades",
          "To organize database records alphabetically"],
         0,
         "The Run-Grow-Transform model balances baseline maintenance ('Run the business'), capability enhancement ('Grow'), and new venture innovation ('Transform')."),

        ("IS Strategy & Hierarchy",
         "What is 'Digital Transformation'?",
         ["Scanning physical paper receipts into PDF format",
          "The profound integration of digital technology across all areas of a business, fundamentally changing how value is created, operations are conducted, and customer experiences are delivered",
          "Buying new desktop computer monitors for executive managers",
          "Sending promotional marketing emails to corporate clients"],
         1,
         "Digital transformation goes beyond digitizing records; it fundamentally reshapes business models, culture, customer journeys, and organizational ecosystems through technology."),

        ("IS Strategy & Hierarchy",
         "What does 'Interoperability' mean in enterprise IT systems?",
         ["The ability of diverse, heterogeneous information systems and software applications to communicate, exchange data, and use the information exchanged seamlessly",
          "The speed at which a computer server restarts after a power failure",
          "A legal dispute between two software vendors regarding copyright",
          "The physical distance between two regional corporate data centers"],
         0,
         "Interoperability ensures disparate platforms, legacy mainframes, and modern cloud microservices can exchange and interpret data coherently (via APIs and open standards)."),

        ("IS Strategy & Hierarchy",
         "What is an 'API' (Application Programming Interface)?",
         ["A software intermediary that allows two distinct applications to talk to and share data with each other using standardized protocols",
          "An annual performance review conducted on software engineers",
          "A mechanical tool used for opening desktop computer cases",
          "An accounting standard used for calculating asset depreciation"],
         0,
         "APIs define protocols and definitions allowing different software systems to communicate, share capabilities, and integrate securely (e.g., RESTful APIs, GraphQL)."),

        ("IS Strategy & Hierarchy",
         "What is 'Service-Oriented Architecture' (SOA)?",
         ["A physical architectural blueprint for building customer service centers",
          "A software design approach where application components provide services to other components via a communication protocol across a network, promoting modularity and reuse",
          "A corporate policy requiring employees to provide excellent customer service",
          "An IT department organizational hierarchy composed of support technicians"],
         1,
         "SOA breaks complex applications into discrete, reusable software services that communicate via standard interfaces, increasing agility and business flexibility."),

        ("IS Strategy & Hierarchy",
         "In modern cloud software engineering, how do 'Microservices' differ from 'Monolithic' architecture?",
         ["Microservices build applications as a suite of small, independent, modular services running in their own processes and communicating via lightweight APIs, rather than a single unified codebase",
          "Microservices only run on mobile smartphones; Monolithic only runs on mainframes",
          "Microservices have zero software code; Monolithic has millions of lines",
          "Microservices cannot connect to the internet"],
         0,
         "Microservices decouple systems into independently deployable, scalable services, eliminating single points of failure and enabling continuous deployment compared to rigid monoliths."),

        ("IS Strategy & Hierarchy",
         "What is 'Legacy System' in corporate IT management?",
         ["A brand new cutting-edge software program launched this month",
          "An outdated computing system, software application, or hardware technology that remains in use because it performs critical functions, despite high maintenance costs and integration challenges",
          "A cash endowment left to an IT university department in a will",
          "A company policy rewarding long-tenured IT employees"],
         1,
         "Legacy systems are mature, mission-critical systems (often written in COBOL or older architectures) that are costly to maintain, rigid, and risky to replace."),

        # --- TOPIC 2: ENTERPRISE APPLICATIONS: ERP, CRM, SCM (26-55) ---
        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is the primary defining characteristic of an 'Enterprise Resource Planning' (ERP) system (e.g., SAP S/4HANA, Oracle ERP)?",
         ["A collection of isolated, separate departmental spreadsheets that never communicate",
          "A centralized, integrated suite of business applications that share a single common database, facilitating real-time data flow across all business functions (Finance, HR, Manufacturing, Sales)",
          "A desktop graphic design software program used for marketing posters",
          "A physical conveyor belt system installed in industrial factories"],
         1,
         "ERP systems integrate core business processes across departments into a unified platform backed by a single central database, eliminating information silos and redundant data entry."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "Which of the following is the most frequent cause of massive cost overruns and failures in corporate ERP implementation projects?",
         ["Purchasing too many server racks",
          "Inadequate change management, excessive software customization, poor data cleansing, and lack of top executive leadership alignment",
          "Selecting a software system that uses SQL databases",
          "Upgrading employee desktop monitors before implementation"],
         1,
         "ERP failures are predominantly socio-technical: organizational resistance to change, lack of business process alignment, over-customization, and weak executive sponsorship."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'Customer Relationship Management' (CRM) software (e.g., Salesforce, HubSpot) primarily designed to achieve?",
         ["Manage end-to-end interactions with current and prospective customers across marketing, sales pipelines, customer service, and retention tracking",
          "Calculate factory equipment depreciation for accounting reports",
          "Automate the printing of shipping container cardboard labels",
          "Monitor employee internet browsing history during work hours"],
         0,
         "CRM systems consolidate customer data, manage sales leads and opportunity funnels, automate customer support ticketing, and optimize customer lifetime engagement."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "In CRM systems, what is the '360-Degree Customer View'?",
         ["A panoramic camera installed in retail storefronts",
          "A comprehensive, unified single view of all customer interactions, purchase history, inquiries, preferences, and touchpoints aggregated across all corporate channels",
          "A rotating carousel display for retail merchandise",
          "An annual customer satisfaction survey sent via postal mail"],
         1,
         "A 360-degree view consolidates all customer interactions across sales, support, social media, web, and billing into a single dashboard for personalized service."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'Supply Chain Management' (SCM) software designed to optimize?",
         ["The physical layout of executive office desks",
          "The end-to-end coordination and flow of materials, information, and finances from initial raw material suppliers through manufacturing to final customer delivery",
          "The internal employee grievance filing process",
          "The design of corporate holiday greeting cards"],
         1,
         "SCM systems streamline procurement, demand forecasting, inventory optimization, production scheduling, and transportation logistics across the supply network."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is the 'Bullwhip Effect' in supply chain management?",
         ["A physical tool used to direct livestock in agricultural operations",
          "The distortion and amplification of demand variability that occurs as information travels upstream from retailers to wholesalers to manufacturers and raw material suppliers",
          "A sudden spike in employee turnover within warehouse facilities",
          "A dramatic drop in corporate stock prices due to supply shortages"],
         1,
         "The bullwhip effect occurs when small fluctuations in retail demand trigger exaggerated swings in upstream supplier orders due to lack of visibility, batch ordering, and lead-time delays."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "How does an integrated SCM system with real-time POS data sharing mitigate the Bullwhip Effect?",
         ["By hiding sales data from upstream suppliers",
          "By providing upstream supply chain partners with transparent, real-time demand signals and synchronized collaborative forecasting (CPFR)",
          "By doubling inventory order sizes at each intermediate warehouse",
          "By switching all transportation to air freight exclusively"],
         1,
         "Collaborative Planning, Forecasting, and Replenishment (CPFR) and shared point-of-sale visibility eliminate guesswork and prevent exaggerated inventory swings."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'Electronic Data Interchange' (EDI)?",
         ["Sending casual emails between purchasing managers",
          "The computer-to-computer exchange of standardized electronic business documents (such as purchase orders, invoices, and shipping notices) between trading partners",
          "An interactive video conferencing call between corporate directors",
          "A digital signature captured on a mobile touchscreen device"],
         1,
         "EDI enables automated, structured, B2B exchange of commercial transaction documents using standardized protocols (e.g., ANSI X12, EDIFACT), eliminating manual paperwork."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "In ERP systems, what is a 'Vanilla Implementation'?",
         ["Implementing software that is exclusively used in the ice cream industry",
          "Deploying the standard, out-of-the-box ERP system with minimal or zero software code customization, adapting internal business processes to match the software's best-practice workflows",
          "A failed software deployment that produces zero functional output",
          "An implementation executed exclusively during summer months"],
         1,
         "A vanilla implementation adapts company processes to standard software workflows, avoiding costly customizations, bugs, and difficult future software upgrades."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'Supply Chain Visibility'?",
         ["Installing transparent glass walls in warehouse facilities",
          "The ability of supply chain stakeholders to track components, sub-assemblies, and finished products in real-time as they travel from supplier origins to final destinations",
          "Printing shipping manifests in large fluorescent fonts",
          "Allowing customers to visit factory manufacturing floors on guided tours"],
         1,
         "Supply chain visibility leverages IoT sensors, RFID tags, GPS tracking, and cloud dashboards to provide real-time tracking of cargo location, condition, and status."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What does 'SRM' stand for in enterprise software suites?",
         ["Supplier Relationship Management", "Standard Resource Measurement", "System Risk Mitigation", "Sales Revenue Model"],
         0,
         "SRM software focuses on managing and optimizing procurement relationships, supplier evaluations, contract compliance, and supplier collaboration."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'RFID' (Radio Frequency Identification) technology commonly used for in supply chains?",
         ["Transmitting radio music broadcasts to factory workers",
          "Automated, wireless tracking and identification of inventory items, pallets, and assets using radio waves without requiring direct optical line-of-sight scanning",
          "Encrypting executive email communications",
          "Measuring ambient room temperatures in corporate offices"],
         1,
         "RFID tags transmit data via radio signals to scanners without direct line-of-sight, enabling rapid bulk inventory counting, pallet tracking, and theft prevention."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "In CRM analytics, what is 'Recency, Frequency, and Monetary' (RFM) analysis?",
         ["A method for evaluating customer value by analyzing how recently a customer purchased, how often they purchase, and how much money they spend",
          "A financial formula for calculating employee payroll overtime bonuses",
          "A radio frequency measurement technique for wireless routers",
          "An accounting audit method for calculating corporate income tax"],
         0,
         "RFM segmentation groups customers based on transaction behavior (Recency, Frequency, Monetary spend) to tailor targeted marketing campaigns and retention efforts."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'Sales Force Automation' (SFA) in CRM systems?",
         ["Replacing human sales representatives with mechanical robotic androids",
          "Software capabilities that automate routine sales pipeline activities such as lead tracking, contact management, sales forecasting, order processing, and follow-up scheduling",
          "A corporate training program for retail cashiers",
          "A statutory labor law mandating minimum commissions for sales personnel"],
         1,
         "SFA streamlines and automates administrative sales pipeline workflows, allowing sales reps to focus on relationship building and deal closing."),

        ("Enterprise Applications (ERP, CRM, SCM)",
         "What is 'Vendor-Managed Inventory' (VMI)?",
         ["When the customer takes full ownership of the supplier's manufacturing plant",
          "A collaborative supply chain practice where the supplier (vendor) is responsible for monitoring customer inventory levels and replenishing stock at the customer's facility as needed",
          "When a business sells all inventory at a 90% discount to liquidators",
          "A software tool that blocks third-party vendors from accessing company data"],
         1,
         "Under VMI, the supplier has visibility into the buyer's inventory consumption and takes responsibility for maintaining agreed-upon stock levels, reducing stockouts and holding costs."),

        # --- TOPIC 3: DATA MANAGEMENT, DBMS, SQL, BIG DATA & BI (56-90) ---
        ("Data Management, DBMS & Big Data",
         "In a Relational Database Management System (RDBMS), what is a 'Primary Key'?",
         ["A physical brass key used to unlock the server cabinet",
          "A column or set of columns that uniquely identifies each individual row/record in a database table",
          "The first employee hired in the IT department",
          "A password used to log into the corporate email client"],
         1,
         "A Primary Key enforces entity integrity by ensuring every record in a relational database table is uniquely identifiable and non-null."),

        ("Data Management, DBMS & Big Data",
         "What is a 'Foreign Key' in relational database design?",
         ["A database column containing international currency symbols",
          "A field in one table that uniquely references and links to the primary key in another table, establishing a relationship between the two tables",
          "A password used by foreign remote employees",
          "A cryptographic key issued by foreign sovereign governments"],
         1,
         "Foreign keys enforce referential integrity across related tables, linking child records to parent entity primary keys."),

        ("Data Management, DBMS & Big Data",
         "What does 'SQL' stand for, and what is its primary function?",
         ["Structured Query Language; the standard programming language used to define, manipulate, manage, and query data in relational databases",
          "System Quality Level; an engineering rating for server performance",
          "Sales Quantity List; a monthly report of retail transactions",
          "Software Quick Link; a browser bookmark tool"],
         0,
         "SQL is the domain-specific standard language used for querying, updating, inserting, and managing data stored in relational database systems."),

        ("Data Management, DBMS & Big Data",
         "What is 'Database Normalization'?",
         ["Converting all text data to uppercase letters",
          "The systematic process of structuring a relational database (typically to 3NF) to reduce data redundancy, eliminate update anomalies, and ensure data integrity",
          "Deleting historical records older than twelve months",
          "Standardizing the physical dimensions of hard disk drives"],
         1,
         "Normalization organizes tables to minimize data duplication and prevent insert, update, and delete anomalies (e.g., 1NF, 2NF, 3NF)."),

        ("Data Management, DBMS & Big Data",
         "What are the 'ACID' properties in transactional database management systems?",
         ["Accuracy, Complexity, Integrity, and Durability",
          "Atomicity, Consistency, Isolation, and Durability",
          "Authorization, Cryptography, Identity, and Decentralization",
          "Aggregation, Calculation, Indexing, and Distribution"],
         1,
         "ACID guarantees that database transactions are processed reliably: Atomicity (all or nothing), Consistency (valid state), Isolation (independent execution), Durability (persisted)."),

        ("Data Management, DBMS & Big Data",
         "What is the difference between 'OLTP' and 'OLAP' systems?",
         ["OLTP (Online Transaction Processing) is optimized for fast, real-time transactional processing of daily operations; OLAP (Online Analytical Processing) is optimized for complex queries, historical aggregation, and multidimensional analysis",
          "OLTP is used only on weekends; OLAP is used during weekdays",
          "OLTP stores audio files; OLAP stores video files",
          "OLTP has zero security; OLAP requires biometric scanning"],
         0,
         "OLTP handles high volumes of rapid, concurrent transactional updates (e.g., banking transactions), while OLAP analyzes consolidated historical data for strategic business intelligence."),

        ("Data Management, DBMS & Big Data",
         "What is a 'Data Warehouse'?",
         ["A physical storage room filled with cardboard boxes of printed paper documents",
          "A centralized, subject-oriented, integrated, time-variant, and non-volatile repository of data collected from multiple operational sources used for analytics and decision-making",
          "A commercial retail storefront that sells computer memory chips",
          "A temporary cache memory on a personal laptop"],
         1,
         "Data warehouses consolidate cleansed historical data from across the enterprise (via ETL) into multidimensional schemas (star/snowflake) for analytical querying."),

        ("Data Management, DBMS & Big Data",
         "In data warehousing, what does 'ETL' stand for?",
         ["Encrypt, Transfer, and Lock",
          "Extract, Transform, and Load",
          "Evaluate, Test, and Launch",
          "Execute, Terminate, and Log"],
         1,
         "ETL describes the pipeline process of Extracting raw data from disparate operational systems, Transforming/cleansing it to business standards, and Loading it into the data warehouse."),

        ("Data Management, DBMS & Big Data",
         "What is a 'Data Lake' compared to a 'Data Warehouse'?",
         ["A data lake stores massive volumes of raw, unstructured, semi-structured, and structured data in its native format until needed; a data warehouse stores structured, pre-processed data in a predefined schema",
          "A data lake is a physical reservoir of water used to cool mainframe servers",
          "A data lake can only hold text files under 1 megabyte in size",
          "A data lake is operated exclusively by municipal water utilities"],
         0,
         "Data lakes store vast amounts of raw data (schema-on-read) using low-cost storage (e.g., Hadoop, Amazon S3), while data warehouses require structured preprocessing (schema-on-write)."),

        ("Data Management, DBMS & Big Data",
         "What are the traditional 'Four Vs' of Big Data?",
         ["Volume, Velocity, Variety, and Veracity",
          "Validation, Vision, Value, and Viability",
          "Virtualization, Vulnerability, Vector, and Voltage",
          "Venture, Variable, Version, and Volume"],
         0,
         "Big Data is characterized by high Volume (scale of data), Velocity (speed of generation/streaming), Variety (diverse formats: text, video, logs), and Veracity (data trustworthiness/quality)."),

        ("Data Management, DBMS & Big Data",
         "What is 'NoSQL' (Not Only SQL) database technology designed for?",
         ["Managing strictly non-digital paper documents",
          "Handling massive volumes of unstructured or semi-structured data, dynamic schemas, and horizontal scaling across distributed server clusters (e.g., MongoDB, Cassandra)",
          "A database system that prohibits queries of any kind",
          "A database that can only store numeric integers"],
         1,
         "NoSQL databases (Document, Key-Value, Columnar, Graph) provide flexible schemas and horizontal scalability for distributed, high-throughput modern applications."),

        ("Data Management, DBMS & Big Data",
         "What is 'Data Mining'?",
         ["Physically digging underground tunnels to lay fiber optic cables",
          "The computational process of discovering hidden patterns, anomalies, correlations, and actionable insights in large datasets using machine learning, statistics, and AI",
          "Deleting corrupted sectors on magnetic hard disks",
          "Manually typing customer phone numbers into spreadsheet cells"],
         1,
         "Data mining extracts predictive patterns and previously unknown relationships from big datasets (e.g., market basket association rules, customer churn prediction)."),

        ("Data Management, DBMS & Big Data",
         "What is 'Business Intelligence' (BI)?",
         ["An executive's biological IQ score measured during an interview",
          "The technology-driven process and applications used for analyzing data, presenting actionable information, and helping executives and managers make informed business decisions",
          "A corporate intelligence agency conducting industrial espionage",
          "The instruction manual provided with computer hardware"],
         1,
         "BI encompasses the tools, practices, and platforms (e.g., PowerBI, Tableau) that transform raw enterprise data into interactive visualizations, reports, and strategic insights."),

        ("Data Management, DBMS & Big Data",
         "What is 'Data Governance'?",
         ["A parliamentary committee that regulates consumer electronics prices",
          "The overall management of the availability, usability, integrity, consistency, and security of data used in an enterprise, governed by formal policies and standards",
          "The legal ownership of physical computer monitors by the company",
          "A government department that collects corporate income taxes"],
         1,
         "Data Governance establishes accountability, data quality standards, stewardship, access permissions, and regulatory compliance (e.g., GDPR) across enterprise data assets."),

        ("Data Management, DBMS & Big Data",
         "What is 'Master Data Management' (MDM)?",
         ["A master password that opens all corporate user accounts",
          "A comprehensive method of enabling an enterprise to link all of its critical core data (such as customer, product, employee, and supplier entities) to a single, authoritative master record ('Single Version of the Truth')",
          "The training program completed by database administrators",
          "A software program used exclusively for backing up personal photos"],
         1,
         "MDM creates a single, consistent, authoritative golden record of foundational enterprise entities across disparate business applications."),

        # --- TOPIC 4: CLOUD COMPUTING & INFRASTRUCTURE (91-115) ---
        ("Cloud Computing & Infrastructure",
         "In Cloud Computing, what does 'IaaS' (Infrastructure as a Service) provide to the client?",
         ["Ready-to-use end-user applications delivered via a web browser (e.g., Gmail, Salesforce)",
          "On-demand access to fundamental computing resources such as virtual machines, raw storage, and virtual networking, where the client manages the OS, middleware, and applications (e.g., AWS EC2)",
          "A managed platform environment for developers to build and deploy apps without managing underlying servers (e.g., Heroku)",
          "Physical computer monitors delivered by postal mail"],
         1,
         "IaaS delivers raw infrastructure (virtual servers, storage, firewalls) where the customer manages the operating system, runtime, and software stack."),

        ("Cloud Computing & Infrastructure",
         "What does 'PaaS' (Platform as a Service) deliver?",
         ["A cloud development and deployment environment that provides operating systems, execution runtimes, databases, and web servers, allowing developers to build apps without managing server infrastructure (e.g., Google App Engine)",
          "A physical desk for laptop placement in offices",
          "Raw unformatted hard disk drives shipped to company headquarters",
          "A turnkey customer relationship management web application"],
         0,
         "PaaS provides hardware and software tools over the internet, allowing software developers to build, test, and host applications without managing underlying infrastructure."),

        ("Cloud Computing & Infrastructure",
         "What is 'SaaS' (Software as a Service)?",
         ["Software delivered over the internet via a web browser on a subscription basis, where the cloud provider manages all underlying infrastructure, code, and maintenance (e.g., Microsoft 365, Salesforce)",
          "Software printed on paper instruction cards",
          "A custom operating system developed internally by a single company",
          "A software program that can only run without an internet connection"],
         0,
         "SaaS delivers fully managed end-user software applications over the web, eliminating client-side installation, patching, and infrastructure management."),

        ("Cloud Computing & Infrastructure",
         "What is a 'Hybrid Cloud' architecture?",
         ["A computing environment that combines and coordinates on-premises private cloud infrastructure with third-party public cloud services, allowing data and apps to be shared between them",
          "A cloud server powered by both solar panels and gasoline generators",
          "A software application that works on both Windows and MacOS",
          "A cloud provider owned jointly by two competing sovereign governments"],
         0,
         "Hybrid cloud provides flexibility and data sovereignty by keeping sensitive mission-critical workloads on private clouds/on-premise while bursting scalable workloads to public clouds."),

        ("Cloud Computing & Infrastructure",
         "What is 'Elasticity' (or Scalability) in cloud computing?",
         ["The physical flexibility of plastic ethernet cables",
          "The ability of a cloud system to dynamically provision and de-provision computing power, memory, and storage in real-time to match fluctuating workload demands automatically",
          "The ability of employees to work from home on alternate Fridays",
          "A contract clause allowing software prices to increase by 20%"],
         1,
         "Cloud elasticity enables dynamic auto-scaling: expanding server capacity during demand spikes (e.g., Black Friday) and scaling down to save costs when traffic recedes."),

        ("Cloud Computing & Infrastructure",
         "What is 'Virtualization' in cloud and data center architecture?",
         ["The creation of virtual software representations of physical hardware assets (such as virtual servers, storage devices, and networks) using a hypervisor",
          "Playing 3D video games during lunch breaks in the office",
          "A digital drawing of a proposed physical building",
          "Conducting board meetings via teleconference call"],
         0,
         "Virtualization uses a hypervisor (e.g., VMware, KVM) to run multiple isolated virtual machines on a single physical server, maximizing hardware utilization and efficiency."),

        ("Cloud Computing & Infrastructure",
         "What is 'Serverless Computing' (e.g., AWS Lambda)?",
         ["A computing model where computers operate without physical silicon microchips",
          "A cloud execution model where the cloud provider dynamically manages server allocation and machine provisioning, charging only for the precise compute time consumed by executing functions",
          "A company operating entirely without an internet connection",
          "A peer-to-peer cryptocurrency network running on personal smartphones"],
         1,
         "Serverless (Function-as-a-Service) abstracts server management completely; developers execute code event-driven, paying exclusively for exact millisecond execution time."),

        ("Cloud Computing & Infrastructure",
         "What is 'Edge Computing'?",
         ["Placing computer monitors near the physical edges of office desks",
          "A distributed computing paradigm that processes data near the source of data generation (e.g., IoT devices, local gateways) rather than relying solely on a centralized distant cloud data center, reducing latency",
          "An extreme programming technique used by elite software hackers",
          "Running server computers at maximum electrical voltage capacity"],
         1,
         "Edge computing processes sensor and telemetry data locally near devices (e.g., autonomous vehicles, industrial robotics), minimizing latency and bandwidth strain."),

        ("Cloud Computing & Infrastructure",
         "What is a 'Service Level Agreement' (SLA) in cloud service contracts?",
         ["A casual verbal understanding between a vendor and buyer",
          "A legally binding contract that defines specific measurable levels of service performance, uptime availability (e.g., 99.99% 'four nines'), and penalties/credits for outages",
          "A user manual provided to retail software buyers",
          "An employment contract signed by an IT technician"],
         1,
         "An SLA defines guaranteed uptime availability, latency parameters, disaster recovery timelines, and financial remedies if the service provider fails to meet standards."),

        ("Cloud Computing & Infrastructure",
         "What is 'Multi-Tenancy' in cloud architecture?",
         ["Multiple tenants living in a single corporate apartment building",
          "A software architecture where a single instance of a software application serves multiple distinct customer organizations (tenants), while securely isolating each tenant's data and configurations",
          "A company operating five separate corporate headquarters simultaneously",
          "A software license that allows an individual to log in from two laptops"],
         1,
         "Multi-tenancy allows SaaS vendors to serve thousands of customers on a shared infrastructure pool, drastically reducing per-user hosting and maintenance costs."),

        # --- TOPIC 5: CYBERSECURITY, RISK & ETHICS (116-140) ---
        ("Cybersecurity & Information Security",
         "The 'CIA Triad' is the foundational model for information security policies. What does 'CIA' stand for in this context?",
         ["Central Intelligence Agency",
          "Confidentiality, Integrity, and Availability",
          "Control, Inspection, and Authorization",
          "Compliance, Insurance, and Auditing"],
         1,
         "The CIA Triad is the core security benchmark: Confidentiality (privacy/no unauthorized access), Integrity (data accuracy/no tampering), and Availability (systems accessible when needed)."),

        ("Cybersecurity & Information Security",
         "What is 'Phishing' in cyber threat vectors?",
         ["A recreational outdoor fishing activity organized for IT staff",
          "A social engineering attack where malicious actors impersonate legitimate organizations via deceptive emails/messages to trick users into revealing sensitive credentials or downloading malware",
          "A technical process for measuring optical network speed",
          "A method of searching database records using wildcards"],
         1,
         "Phishing relies on psychological manipulation (urgency, spoofed domains) to dupe individuals into surrendering passwords, financial data, or installing malicious payloads."),

        ("Cybersecurity & Information Security",
         "What is 'Ransomware'?",
         ["A fee paid to insurance companies to protect corporate servers",
          "A type of malicious software that encrypts a victim's files or locks their system, demanding a ransom payment in cryptocurrency to restore access or prevent public data leakage",
          "A commercial software subscription fee charged annually",
          "A bonus paid to ethical security researchers who find bugs"],
         1,
         "Ransomware locks critical enterprise files/systems using strong encryption, extorting ransoms under threat of permanent data loss or public exposure."),

        ("Cybersecurity & Information Security",
         "What is a 'Distributed Denial of Service' (DDoS) attack?",
         ["A physical burglary of corporate server hard drives",
          "A cyberattack where a perpetrator overwhelms a target server or network with a flood of fake internet traffic originating from multiple compromised systems (botnets), rendering the service inaccessible to legitimate users",
          "A software bug that causes desktop calculators to crash",
          "An intentional corporate shutdown for scheduled annual maintenance"],
         1,
         "DDoS attacks weaponize distributed networks of infected devices (botnets) to flood network bandwidth or server compute resources, causing service outages."),

        ("Cybersecurity & Information Security",
         "What is 'Two-Factor Authentication' (2FA) / Multi-Factor Authentication (MFA)?",
         ["Entering the same password two times in succession",
          "A security mechanism requiring users to provide two or more distinct verification factors to gain access: something you know (password), something you have (phone/token), or something you are (biometrics)",
          "Having two different employees log in to the same computer simultaneously",
          "Changing corporate passwords every two calendar days"],
         1,
         "MFA substantially reduces account compromise by demanding verification across multiple independent categories (knowledge, possession, inherence)."),

        ("Cybersecurity & Information Security",
         "How does 'Asymmetric Encryption' (Public Key Cryptography) function?",
         ["It uses a single shared secret key for both encryption and decryption",
          "It uses a mathematically linked pair of keys: a Public Key for encrypting data and a Private Key for decrypting data",
          "It converts all text characters into random geometric symbols",
          "It deletes data immediately after transmission to prevent interception"],
         1,
         "Asymmetric cryptography (e.g., RSA, ECC) uses a public key to encrypt data and a private key (held secret by the recipient) to decrypt it, securing internet communications (HTTPS/TLS)."),

        ("Cybersecurity & Information Security",
         "What is a 'Firewall' in network architecture?",
         ["A fireproof brick wall constructed around physical data centers",
          "A network security device or software that monitors and controls incoming and outgoing network traffic based on predetermined security rules, creating a barrier between trusted and untrusted networks",
          "A software tool that accelerates internet download speeds by 50%",
          "An emergency electrical circuit breaker installed in server rooms"],
         1,
         "Firewalls inspect data packets, blocking unauthorized access, malware traffic, and suspicious port activity while permitting authorized corporate communications."),

        ("Cybersecurity & Information Security",
         "What is the 'Zero Trust Architecture' (ZTA) principle in modern enterprise cybersecurity?",
         ["Trusting every internal employee on the local corporate network completely by default",
          "'Never Trust, Always Verify' — requiring strict identity verification and continuous authorization for every user and device attempting to access resources, regardless of whether they are inside or outside the network perimeter",
          "Eliminating all passwords across the enterprise",
          "Operating an organization with zero computers or digital systems"],
         1,
         "Zero Trust assumes breaches are inevitable and eliminates implicit perimeter trust; every request must be authenticated, authorized, and encrypted continuously."),

        ("Cybersecurity & Information Security",
         "What is a 'Zero-Day Vulnerability'?",
         ["A software bug that takes zero days to fix",
          "A software security flaw that is unknown to the vendor or developers and has no official patch available, leaving it vulnerable to exploitation by attackers",
          "A computer system that has operated for zero days without a reboot",
          "A software trial version that expires in twenty-four hours"],
         1,
         "A Zero-Day flaw is an unpatched software vulnerability actively exposed to exploitation before developers have developed or released a security fix."),

        ("Cybersecurity & Information Security",
         "What is 'Social Engineering' in information security?",
         ["Designing open-plan office layouts to encourage employee conversation",
          "The psychological manipulation of people into performing actions or divulging confidential information (e.g., passwords, bank details) rather than technical hacking of software",
          "Teaching software programming in primary school curricula",
          "Writing algorithms for social media recommendation feeds"],
         1,
         "Social engineering exploits human cognitive vulnerabilities (trust, fear, urgency, authority) through impersonation, pretexting, or baiting to breach security."),

        ("Cybersecurity & Information Security",
         "In business continuity management, what is the difference between 'RPO' (Recovery Point Objective) and 'RTO' (Recovery Time Objective)?",
         ["RPO defines the maximum acceptable data loss measured in time (how much data can we lose?); RTO defines the maximum acceptable system downtime to restore operations (how long can we be down?)",
          "RPO is used for marketing; RTO is used for accounting",
          "RPO measures server temperature; RTO measures electricity cost",
          "RPO applies only to public cloud vendors; RTO applies to private banks"],
         0,
         "RPO dictates backup frequency (data loss tolerance), while RTO dictates recovery speed (downtime tolerance) in disaster recovery planning."),

        ("Cybersecurity & Information Security",
         "What is 'Penetration Testing' (Pen Testing)?",
         ["Testing how deeply a physical nail can penetrate computer plastic casings",
          "An authorized simulated cyberattack performed on a computer system, network, or application to evaluate security posture and identify exploitable vulnerabilities before real attackers do",
          "An audit of employee keyboard typing speed",
          "Testing the durability of ethernet cables under physical stress"],
         1,
         "Ethical hackers (white hats) perform authorized penetration tests to uncover security weaknesses, configuration errors, and vulnerabilities for remediation."),

        ("Cybersecurity & Information Security",
         "What is 'Data Sanitization' or 'Data Wiping' before decommissioning enterprise storage drives?",
         ["Cleaning the plastic casing of hard disk drives with disinfectant wipes",
          "The deliberate, permanent, and irreversible removal or overwriting of data stored on a storage device so that it cannot be recovered by any forensic method",
          "Dragging files to the desktop recycle bin and leaving them there",
          "Renaming files so they cannot be found via desktop search"],
         1,
         "Cryptographic erasure or magnetic degaussing ensures proprietary, customer, and financial data cannot be retrieved from retired storage media."),

        # --- TOPIC 6: SYSTEMS DEVELOPMENT LIFE CYCLE (SDLC) & AGILE (141-167) ---
        ("SDLC & Project Methodologies",
         "What is the sequential order of phases in the traditional 'Waterfall' Systems Development Life Cycle (SDLC)?",
         ["Planning, Requirements Analysis, System Design, Implementation (Coding), Testing, Deployment, and Maintenance",
          "Deployment, Maintenance, Planning, Coding, and Testing",
          "Testing, Coding, Requirements, Design, and Decommissioning",
          "Ideation, Monetization, Liquidation, and Termination"],
         0,
         "The classic Waterfall SDLC model executes sequentially: Planning $\rightarrow$ Analysis $\rightarrow$ Design $\rightarrow$ Implementation $\rightarrow$ Testing $\rightarrow$ Deployment $\rightarrow$ Maintenance."),

        ("SDLC & Project Methodologies",
         "What is the primary drawback of the traditional Waterfall methodology for complex, modern software projects?",
         ["It produces software that is too inexpensive",
          "Its rigid, sequential nature makes it difficult and costly to accommodate changing user requirements late in the development cycle, as working software is delivered only at the end",
          "It prohibits developers from writing documentation",
          "It cannot be used with SQL databases"],
         1,
         "Waterfall struggles in dynamic environments because requirement changes late in development require costly rework, and working software is not delivered until late phases."),

        ("SDLC & Project Methodologies",
         "The 'Agile Manifesto' prioritizes which of the following values over comprehensive documentation?",
         ["Rigid contract negotiation", "Working software", "Following a strict five-year plan", "Strict departmental silos"],
         1,
         "The Agile Manifesto values: Individuals and interactions over processes and tools; Working software over comprehensive documentation; Customer collaboration over contract negotiation; Responding to change over following a plan."),

        ("SDLC & Project Methodologies",
         "In Scrum methodology, what is a 'Sprint'?",
         ["A fast race run by software engineers around the office park",
          "A fixed-length, repeatable time-box (typically 1 to 4 weeks) during which a 'Done', usable, and potentially releasable product increment is created",
          "A mandatory 24-hour overtime coding session",
          "An annual performance review meeting with senior executives"],
         1,
         "A Sprint is a fixed 1-4 week iteration where a cross-functional Scrum team delivers a validated, testable increment of software functionality."),

        ("SDLC & Project Methodologies",
         "What is the primary role of the 'Product Owner' in a Scrum development team?",
         ["Managing the physical office furniture budget",
          "Defining the product vision, managing and prioritizing the Product Backlog, and ensuring the development team delivers maximum business value to stakeholders",
          "Writing 100% of the software programming code personally",
          "Conducting daily disciplinary hearings for junior developers"],
         1,
         "The Product Owner represents customer/business stakeholders, prioritizes backlog user stories, and clarifies acceptance criteria for the development team."),

        ("SDLC & Project Methodologies",
         "What is the role of the 'Scrum Master'?",
         ["A senior corporate executive who fires underperforming engineers",
          "A servant-leader and coach who helps the Scrum team follow Agile principles, facilitates Scrum ceremonies, and removes impediments (blockers) to team progress",
          "The lead database architect who designs SQL tables",
          "The chief financial officer who approves payroll checks"],
         1,
         "The Scrum Master acts as a facilitator and servant-leader, removing operational blockers, shielding the team from distractions, and coaching Agile practices."),

        ("SDLC & Project Methodologies",
         "What is the purpose of the 'Daily Stand-up' (Daily Scrum) meeting?",
         ["A 2-hour formal presentation to corporate board members",
          "A brief 15-minute synchronization meeting where team members answer: What did I do yesterday? What will I do today? Are there any blockers in my way?",
          "A mandatory physical fitness inspection conducted by human resources",
          "A line-by-line code review of all software programs written that week"],
         1,
         "The Daily Standup is a concise, 15-minute daily sync for the team to inspect progress toward the Sprint Goal and flag impediments."),

        ("SDLC & Project Methodologies",
         "What is 'DevOps'?",
         ["A computer hardware manufacturing union",
          "A set of cultural philosophies, practices, and automated tools that integrates software development (Dev) and IT operations (Ops) to shorten the systems development lifecycle and deliver continuous, high-quality releases (CI/CD)",
          "A type of computer screen used by graphic artists",
          "A programming language developed in the 1970s for mainframes"],
         1,
         "DevOps bridges development and operations through automation (CI/CD pipelines, automated testing, containerization), enabling rapid, reliable, continuous deployment."),

        ("SDLC & Project Methodologies",
         "In software engineering, what is 'CI/CD'?",
         ["Corporate Identity and Customer Delivery",
          "Continuous Integration and Continuous Delivery / Continuous Deployment",
          "Central Interface and Database Compiler",
          "Computer Inspection and Compliance Directory"],
         1,
         "CI/CD automates the building, testing, and deployment of code changes, ensuring rapid feedback and reliable software delivery into production environments."),

        ("SDLC & Project Methodologies",
         "What is 'Kanban' in Agile project management?",
         ["A strict mathematical formula for calculating project budgets",
          "A visual workflow management method that visualizes work items on a board, limits Work-in-Progress (WIP), and optimizes the continuous flow of tasks from backlog to completion",
          "A programming language used for robotics",
          "An annual performance appraisal metric for executives"],
         1,
         "Kanban uses visual boards (To-Do, In-Progress, Review, Done) and explicit WIP limits to optimize flow, prevent bottlenecks, and balance capacity."),

        ("SDLC & Project Methodologies",
         "What is 'User Acceptance Testing' (UAT)?",
         ["Testing whether users can physically plug in computer power cords",
          "The final phase of the software testing process where actual end-users test the system in real-world scenarios to verify it satisfies business requirements before live deployment",
          "Testing whether an employee qualifies for a company credit card",
          "Checking user credit scores before granting internet access"],
         1,
         "UAT is the final gate where business users validate that software functions according to business needs and acceptance criteria before signing off on deployment."),

        ("SDLC & Project Methodologies",
         "What is 'Technical Debt' in software development?",
         ["The monetary bank loans taken out to purchase office laptops",
          "The implied cost of additional future rework and maintenance caused by choosing an easy, fast, or suboptimal coding solution now instead of using a better, well-architected approach",
          "The salary owed to software engineers at the end of the month",
          "The annual depreciation expense of corporate server racks"],
         1,
         "Technical debt accumulates when teams take architectural shortcuts to ship fast; like financial debt, it incurs 'interest' in slower development and maintenance overhead until refactored."),

        ("SDLC & Project Methodologies",
         "What is 'Prototyping' in system requirements analysis?",
         ["Constructing the final commercial software system before gathering user feedback",
          "Building an early, simplified, interactive working model of a system to demonstrate concepts, clarify user requirements, and gather early stakeholder feedback",
          "Writing a 500-page theoretical specification manual",
          "Purchasing server hardware five years before software development begins"],
         1,
         "Prototyping creates mockups or functional wireframes early, helping users visualize workflows and refining requirements before full-scale engineering."),

        ("SDLC & Project Methodologies",
         "What is 'Regression Testing'?",
         ["Testing software on older 1990s computer monitors",
          "Re-running functional and non-functional tests to ensure that newly developed code changes, bug fixes, or enhancements have not adversely affected or broken existing features",
          "Testing software while running development teams in reverse hierarchy",
          "Measuring employee typing speed decline over a working day"],
         1,
         "Regression testing verifies that new code releases or patches do not unintentionally break previously working features in the application."),

        ("SDLC & Project Methodologies",
         "What is 'Change Management' (e.g., Prosci ADKAR model) in IT system implementation?",
         ["Upgrading computer server operating systems during scheduled maintenance",
          "A structured approach to supporting individuals, teams, and organizations in transitioning from a current state to a desired future state when adopting new technological systems and processes",
          "Swapping paper currency for corporate cryptocurrency tokens",
          "Replacing broken office furniture with ergonomic desks"],
         1,
         "Change management addresses the human side of IT adoption—communication, training, coaching, and overcoming resistance—to ensure systems are embraced and utilized.")
    ]

    for i, (topic, q, opts, ans, exp) in enumerate(raw, 1):
        q_data.append({
            "id": f"MBA8105_{i:03d}",
            "courseCode": course_code,
            "courseTitle": course_title,
            "topic": topic,
            "question": q,
            "options": opts,
            "correctAnswer": ans,
            "explanation": exp
        })

    return q_data

if __name__ == "__main__":
    qs = get_questions()
    print(f"Generated {len(qs)} questions for MBA 8105.")
