# scripts/gen_mba8111.py
# 166 High-Yield MBA Questions for MBA 8111: Operations Management

def get_questions():
    course_code = "MBA 8111"
    course_title = "Operations Management"
    q_data = []

    raw = [
        # --- TOPIC 1: OPERATIONS STRATEGY, PRODUCTIVITY & CAPACITY (1-30) ---
        ("Operations Strategy & Productivity",
         "How is 'Multi-Factor Productivity' mathematically calculated?",
         ["Total Units Produced divided by Direct Labor Hours only",
          "Total Value of Outputs divided by Total Cost of Multiple Combined Inputs (e.g., Labor + Material + Energy + Capital + Overhead)",
          "Net Income minus Corporation Tax divided by Total Assets",
          "Total Inventory in Stock divided by Warehouse Square Footage"],
         1,
         "Multi-Factor Productivity = Total Outputs / (Labor + Materials + Energy + Capital + Overhead), capturing overall resource conversion efficiency."),

        ("Operations Strategy & Productivity",
         "What is 'Little's Law' in process analysis and queuing theory?",
         ["Profit = Revenue - Expenses",
          "Average Work-in-Process Inventory ($I$) = Throughput Rate ($R$) $\times$ Flow Time ($T$) ($I = R \times T$)",
          "Price = Cost $\times$ Markup Percentage",
          "Defects = Total Opportunities $\times$ 3.4"],
         1,
         "Little's Law ($I = R \times T$) fundamental to operations: average inventory equals the throughput rate multiplied by average flow time through the process."),

        ("Operations Strategy & Productivity",
         "In process flow analysis, what is the 'Bottleneck'?",
         ["The widest pipe in the factory plumbing infrastructure",
          "The process step or stage with the lowest capacity or longest processing time, which limits the maximum throughput rate of the entire system",
          "The executive manager who signs raw material purchase invoices",
          "A storage rack used for glass beverage bottles"],
         1,
         "A bottleneck is the resource with the smallest capacity/longest cycle time, determining the maximum throughput rate of the whole process."),

        ("Operations Strategy & Productivity",
         "What is 'Cycle Time' in a manufacturing or service process?",
         ["The total time a worker spends commuting to the factory",
          "The average time between the completion of successive units of output in a process",
          "The time required to clean and paint factory floors annually",
          "The duration of a product's patent protection"],
         1,
         "Cycle time is the recurring interval at which successive completed units emerge from a process (e.g., one car every 60 seconds)."),

        ("Operations Strategy & Productivity",
         "What is the difference between 'Design Capacity' and 'Effective Capacity'?",
         ["Design Capacity is the theoretical maximum output achievable under ideal conditions; Effective Capacity is the realistic output expected given maintenance, product mix, scheduling, and breaks",
          "Design Capacity applies only to graphic artists; Effective Capacity applies to accountants",
          "Design Capacity is measured in dollars; Effective Capacity is measured in kilograms",
          "There is zero difference between the two terms"],
         0,
         "Design capacity represents theoretical engineering ceiling; effective capacity accounts for operational realities (changeovers, maintenance, shifts)."),

        ("Operations Strategy & Productivity",
         "How is 'Capacity Utilization' calculated?",
         ["Actual Output divided by Design Capacity (expressed as a percentage)",
          "Effective Capacity divided by Design Capacity",
          "Actual Output divided by Effective Capacity (which is Efficiency)",
          "Design Capacity multiplied by Selling Price"],
         0,
         "Utilization = $(Actual\ Output / Design\ Capacity) \times 100\%$. (Efficiency = $[Actual\ Output / Effective\ Capacity] \times 100\%$)."),

        ("Operations Strategy & Productivity",
         "What is 'Economies of Scale' in manufacturing operations?",
         ["A decrease in average unit cost of production as total production volume increases, due to fixed overhead spreading and learning curve efficiencies",
          "An increase in unit costs caused by factory overcrowding",
          "The physical weighing scales used in shipping warehouses",
          "A financial penalty levied by customs authorities on bulk exports"],
         0,
         "Economies of scale occur when expanding production volume reduces average per-unit costs by distributing fixed capital over more units and boosting specialization."),

        ("Operations Strategy & Productivity",
         "What is 'Diseconomies of Scale'?",
         ["A decrease in fixed overhead expenses",
          "An increase in average unit costs that occurs when an operational facility becomes excessively large, leading to bureaucratic complexity, coordination bottlenecks, and communication breakdown",
          "The discount offered by suppliers for buying in bulk",
          "An economic theory proving that small factories never make profits"],
         1,
         "Diseconomies of scale occur beyond optimal plant scale when administrative friction, communication lags, and logistics congestion raise unit costs."),

        ("Operations Strategy & Productivity",
         "In facility location analysis, the 'Center of Gravity Method' is used to:",
         ["Find the physical center of gravity of heavy manufacturing equipment to balance floor loads",
          "Identify the optimal geographical location for a centralized distribution center or warehouse to minimize total transportation and shipping costs to multiple destination markets",
          "Calculate earthquake resistance standards for warehouse structures",
          "Determine the exact geographic center of a country's landmass"],
         1,
         "The Center of Gravity method mathematically locates a central distribution facility based on market coordinates and shipping volume weights ($x = \frac{\sum x_i W_i}{\sum W_i}$), minimizing freight costs."),

        ("Operations Strategy & Productivity",
         "In assembly line balancing, what is 'Takt Time'?",
         ["The time workers spend taking coffee breaks",
          "The pace of production needed to match the rate of customer demand ($Takt\ Time = \frac{Available\ Net\ Production\ Time}{Customer\ Demand}$)",
          "The time required to clean factory machines at the end of a shift",
          "The shipping transit time from factory to retail store"],
         1,
         "Takt time (from the German word for musical beat) sets the rhythmic manufacturing pace: the rate at which units must be completed to satisfy demand exactly."),

        # --- TOPIC 2: INVENTORY MANAGEMENT & EOQ (31-65) ---
        ("Inventory Management & EOQ",
         "What is the mathematical formula for the basic 'Economic Order Quantity' (EOQ)?",
         ["$EOQ = \sqrt{\frac{2DS}{H}}$ (where $D$ = Annual Demand, $S$ = Order/Setup Cost, $H$ = Annual Holding/Carrying Cost per unit)",
          "$EOQ = \frac{D \times S}{H}$",
          "$EOQ = \sqrt{\frac{D + S}{2H}}$",
          "$EOQ = 2D + S - H$"],
         0,
         "The classic Wilson EOQ formula balances annual ordering costs and inventory holding costs: $EOQ = \sqrt{\frac{2DS}{H}}$."),

        ("Inventory Management & EOQ",
         "At the Economic Order Quantity (EOQ), what is the relationship between Annual Ordering Costs and Annual Holding Costs?",
         ["Annual Ordering Costs are ten times higher than Annual Holding Costs",
          "Annual Ordering Costs and Annual Holding Costs are exactly equal to each other",
          "Annual Holding Costs are zero",
          "Annual Ordering Costs are zero"],
         1,
         "At the EOQ point on the total cost curve, the annual holding cost curve intersects the annual ordering cost curve, making them exactly equal ($Annual\ Holding\ Cost = Annual\ Ordering\ Cost$)."),

        ("Inventory Management & EOQ",
         "What are the core assumptions of the basic EOQ model?",
         ["Demand is constant and known, lead time is known and constant, purchase price is constant (no quantity discounts), order arrives in a single batch, and stockouts are not allowed",
          "Demand is wildly unpredictable and changes randomly every hour",
          "Holding inventory incurs zero carrying cost",
          "Suppliers deliver inventory in partial random shipments over multiple years"],
         0,
         "Classic EOQ assumes constant deterministic demand, fixed lead times, instantaneous batch delivery, fixed unit cost, and no allowable stockouts."),

        ("Inventory Management & EOQ",
         "What is 'Safety Stock' in inventory control?",
         ["Emergency fire extinguishers placed in warehouse aisles",
          "Extra buffer inventory held to mitigate the risk of stockouts caused by unpredictable demand surges or supplier lead-time delays",
          "Damaged inventory returned by customers awaiting destruction",
          "The maximum inventory capacity allowed by municipal fire codes"],
         1,
         "Safety stock acts as a protective buffer against demand variability and supply lead-time uncertainty ($Safety\ Stock = z \times \sigma_{dL}$)."),

        ("Inventory Management & EOQ",
         "In inventory management, the 'Reorder Point' (ROP) under constant demand and lead time is calculated as:",
         ["$ROP = \text{Lead Time Demand} = d \times L$ (where $d$ = daily demand rate, $L$ = supplier lead time in days)",
          "$ROP = \text{Annual Demand} / 365$",
          "$ROP = \text{Holding Cost} \times \text{Ordering Cost}$",
          "$ROP = \text{Warehouse Capacity} - \text{Current Stock}$"],
         0,
         "Reorder Point specifies the inventory level that triggers placing a replenishment order: $ROP = (d \times L) + Safety\ Stock$."),

        ("Inventory Management & EOQ",
         "In 'ABC Inventory Classification' based on the Pareto Principle, 'Class A' items typically represent:",
         ["Approximately 70-80% of total dollar inventory value, but only about 15-20% of total physical inventory items",
          "90% of physical inventory volume with 5% of dollar value",
          "Defective parts that must be scrapped immediately",
          "Items that are ordered once every twenty years"],
         0,
         "Class A items are high-value/critical items requiring tight control; Class B are moderate value; Class C represent bulk items with low dollar value."),

        ("Inventory Management & EOQ",
         "What is the difference between a 'Continuous Review System' (Q-System) and a 'Periodic Review System' (P-System)?",
         ["In a Q-System, inventory is tracked continuously and a fixed order quantity ($Q$) is placed whenever stock drops to the Reorder Point; In a P-System, inventory is reviewed at fixed time intervals ($P$) and a variable quantity is ordered up to a target level",
          "Q-System is used only for perishable food; P-System is used for steel",
          "Q-System requires zero records; P-System requires mainframe computers",
          "Q-System has zero holding costs; P-System has zero ordering costs"],
         0,
         "Q-System monitors stock continuously and orders fixed $Q$ when hitting $ROP$; P-System reviews stock at fixed intervals $T$ and orders variable $Q$ to reach max capacity."),

        ("Inventory Management & EOQ",
         "What are 'Inventory Carrying (Holding) Costs' composed of?",
         ["Capital cost (opportunity cost of money tied up), storage space costs, insurance, taxes, obsolescence, damage, and pilferage/spoilage",
          "The postage fees paid to mail invoice letters to suppliers",
          "The base wholesale purchase price paid for raw materials",
          "The commission paid to external sales agents"],
         1,
         "Holding costs (typically 20-30% of inventory value annually) include cost of capital, warehousing space, insurance, handling, depreciation, shrinkage, and obsolescence."),

        # --- TOPIC 3: LEAN MANUFACTURING, JIT & TOYOTA PRODUCTION SYSTEM (66-100) ---
        ("Lean Production & JIT",
         "In the Toyota Production System (TPS) developed by Taiichi Ohno, what is 'Muda'?",
         ["A ceremonial Japanese factory opening ceremony",
          "Any activity or consumption of resources that adds cost or time without creating value for the customer (Waste)",
          "An advanced robotic welding arm",
          "A formal bonus granted to top-performing assembly workers"],
         1,
         "Muda means waste—any non-value-adding activity across the seven classic wastes: Overproduction, Waiting, Transport, Overprocessing, Inventory, Motion, and Defects."),

        ("Lean Production & JIT",
         "Which of the 7 classic wastes (Muda) is considered the 'worst' or most dangerous by Taiichi Ohno because it hides all other production problems?",
         ["Waste of Overproduction", "Waste of Motion", "Waste of Waiting", "Waste of Transportation"],
         0,
         "Overproduction creates excess inventory that conceals equipment breakdowns, defect rates, bottleneck delays, and scheduling imbalances."),

        ("Lean Production & JIT",
         "What does 'Kanban' literally translate to, and how is it used in Lean/JIT production?",
         ["'Visual Card' or 'Signboard'; a visual signaling system used to authorize production and material movement in a pull production system",
          "'Fast Assembly'; an automated conveyor belt system",
          "'Master Craftsman'; the title given to the chief plant engineer",
          "'Zero Defects'; a mathematical formula for quality auditing"],
         0,
         "Kanban uses cards/containers to signal downstream demand upstream, ensuring parts are produced only when actually consumed (pull system)."),

        ("Lean Production & JIT",
         "What is the difference between a 'Push System' (e.g., traditional MRP) and a 'Pull System' (e.g., JIT/Kanban)?",
         ["In a Push system, goods are produced according to a forecasted schedule and pushed downstream into inventory; in a Pull system, production is triggered only by actual downstream customer consumption",
          "Push systems use manual labor; Pull systems use electric motors",
          "Push systems operate without managers; Pull systems have ten CEOs",
          "Push systems produce zero inventory; Pull systems fill entire warehouses"],
         0,
         "Push systems build to forecast and hold inventory buffers; pull systems (Lean/JIT) build to actual demand, minimizing WIP and inventory holding."),

        ("Lean Production & JIT",
         "What are the '5S' workplace organization methodology steps (translated from Japanese)?",
         ["Sort (Seiri), Set in Order (Seiton), Shine (Seiso), Standardize (Seiketsu), and Sustain (Shitsuke)",
          "Speed, Stamina, Strength, Strategy, and Success",
          "Sales, Shipping, Storage, Safety, and Security",
          "Software, Silicon, Sensors, Storage, and Servers"],
         0,
         "5S establishes visual workplace efficiency: Sort (eliminate unneeded), Set in Order (arrange/label), Shine (clean/inspect), Standardize (protocols), Sustain (discipline)."),

        ("Lean Production & JIT",
         "What is 'SMED' (Single-Minute Exchange of Die) developed by Shigeo Shingo?",
         ["A system for running factory machines for single minutes at a time",
          "A lean methodology for dramatically reducing equipment setup and changeover times to single-digit minutes (under 10 minutes) by converting internal setups to external setups",
          "A financial derivatives trading system for foreign exchange",
          "A single-minute disciplinary meeting held for tardy workers"],
         1,
         "SMED drastically slashes machine changeover downtime (under 10 mins) by separating internal tasks (done when stopped) from external tasks (done while running), enabling small-batch manufacturing."),

        ("Lean Production & JIT",
         "What is 'Andon' in lean manufacturing?",
         ["A visual or audible signaling system (like an overhead light board or cord) that alerts operators and supervisors to a problem on the production line, allowing the line to be stopped immediately",
          "A Japanese tea room constructed inside factory break areas",
          "A mechanical safety lock installed on electrical generators",
          "A spreadsheet template used for calculating employee bonuses"],
         0,
         "Andon is a visual control alert system empowering line workers to flag quality defects and stop production (Jidoka) until root causes are fixed."),

        ("Lean Production & JIT",
         "What is 'Jidoka' (Autonomation) in the Toyota Production System?",
         ["Fully automating the factory so no humans work there",
          "'Automation with a human touch' — equipping machines with the intelligence to automatically detect abnormalities, defects, or malfunctions and immediately stop production",
          "Replacing metal parts with plastic components to reduce weight",
          "A corporate hiring policy for assembly workers"],
         1,
         "Jidoka prevents the propagation of defective units by designing machines that automatically stop when an anomaly occurs, ensuring quality at the source."),

        ("Lean Production & JIT",
         "What is 'Value Stream Mapping' (VSM) in lean process design?",
         ["A geographic road atlas showing truck delivery routes",
          "A visual flowchart tool that documents every step, material flow, and information flow required to bring a product from raw material to customer, separating value-adding from non-value-adding activities",
          "A financial chart comparing corporate stock prices over five years",
          "A software architecture diagram for database tables"],
         1,
         "VSM maps material and information flows from end to end, highlighting cycle times, lead times, WIP inventory, and waste to design an optimized Future State map."),

        ("Lean Production & JIT",
         "What is 'Heijunka' in Lean operations?",
         ["Production leveling and smoothing of volume and product mix over time to eliminate spikes and unevenness (Mura)",
          "A violent labor strike conducted by manufacturing unions",
          "A high-speed automated conveyor system",
          "A legal copyright filed for mechanical patents"],
         0,
         "Heijunka levels production schedules by producing mixed batches in small, steady quantities rather than giant sporadic batches, stabilizing supply chains."),

        # --- TOPIC 4: STATISTICAL QUALITY CONTROL & SIX SIGMA (101-130) ---
        ("Statistical Quality Control",
         "What is the difference between 'Variable Data' and 'Attribute Data' in Statistical Quality Control (SQC)?",
         ["Variable data are continuous quantitative measurements (e.g., length, weight, temperature, voltage); Attribute data are discrete qualitative counts (e.g., conforming vs. non-conforming, number of defects)",
          "Variable data applies only to software; Attribute data applies only to hardware",
          "Variable data is always zero; Attribute data is always infinite",
          "There is no mathematical difference"],
         0,
         "Variable data (continuous measures: weight, diameter) use $\bar{X}$ and $R$ charts; Attribute data (pass/fail, defect counts) use $p$-charts and $c$-charts."),

        ("Statistical Quality Control",
         "Which control charts are used for monitoring the process mean and process dispersion of continuous variable data?",
         ["$p$-chart and $c$-chart", "$\bar{X}$-chart (Mean chart) and $R$-chart (Range chart)", "Pareto chart and Fishbone diagram", "Gantt chart and Flowchart"],
         1,
         "$\bar{X}$-charts track central tendency (process mean) and $R$-charts track variability/spread (range) for continuous variables."),

        ("Statistical Quality Control",
         "Which control chart is appropriate for monitoring the 'proportion or fraction of defective units' in attribute sampling?",
         ["$\bar{X}$-chart", "$R$-chart", "$p$-chart", "$c$-chart"],
         2,
         "A $p$-chart monitors the proportion/fraction of defective items in samples; a $c$-chart monitors the total count of defects per unit."),

        ("Statistical Quality Control",
         "In statistical process control, what does 'Upper Control Limit' (UCL) and 'Lower Control Limit' (LCL) typically represent?",
         ["The engineering specification tolerances dictated by customer blueprints",
          "$\pm 3$ standard deviations ($\pm 3\sigma$) from the process centerline, capturing 99.73% of normal process variation under common-cause variability",
          "The legal minimum and maximum retail prices permitted by law",
          "The physical height limits of warehouse storage shelves"],
         1,
         "Control limits ($\pm 3\sigma$) represent natural statistical voice-of-the-process variation; values outside these limits signal assignable/special causes."),

        ("Statistical Quality Control",
         "What is the difference between 'Common Cause Variation' (Natural variation) and 'Special Cause Variation' (Assignable variation)?",
         ["Common cause variation is inherent to the stable process design; Special cause variation arises from external, identifiable, and rectifiable anomalies (e.g., broken tool, operator error)",
          "Common cause variation occurs on weekends; Special cause occurs on weekdays",
          "Common cause variation is illegal; Special cause is mandatory",
          "Common cause variation has zero variance"],
         0,
         "Common cause variation is random background noise inherent to the system; Special cause variation is non-random and requires immediate root-cause intervention."),

        ("Statistical Quality Control",
         "What does the 'Process Capability Index' ($C_{pk}$) measure?",
         ["The maximum electrical wattage consumed by factory machinery",
          "The ability of a process to produce output within engineering specification limits, accounting for both process variability and process centering",
          "The speed at which a delivery truck can travel on highways",
          "The number of employees who hold university engineering degrees"],
         1,
         "$C_{pk} = \min\left[\frac{USL - \mu}{3\sigma}, \frac{\mu - LSL}{3\sigma}\right]$. A $C_{pk} \ge 1.33$ or $1.67$ indicates a highly capable, well-centered process."),

        # --- TOPIC 5: PROJECT MANAGEMENT (CPM / PERT) (131-150) ---
        ("Project Management (CPM/PERT)",
         "In the Critical Path Method (CPM), what is the 'Critical Path'?",
         ["The most expensive sequence of tasks in the project budget",
          "The longest continuous sequence of dependent activities through the project network diagram, which dictates the absolute minimum time needed to complete the project",
          "The safest walking path through a construction site marked with yellow paint",
          "The sequence of activities performed exclusively by senior executive directors"],
         1,
         "The Critical Path is the longest path of dependent activities; any delay to an activity on the critical path delays the completion date of the entire project."),

        ("Project Management (CPM/PERT)",
         "What is 'Slack Time' (Float) for a project activity?",
         ["The scheduled lunch and break time allocated to project engineers",
          "The amount of time an activity can be delayed without delaying the overall project completion date ($Slack = LS - ES = LF - EF$)",
          "The time lost due to software programming errors",
          "The duration of the project closing celebration dinner"],
         1,
         "Slack (Float) = $LS - ES$ or $LF - EF$. Activities on the Critical Path have zero slack ($Slack = 0$)."),

        ("Project Management (CPM/PERT)",
         "In PERT (Program Evaluation and Review Technique), how is the 'Expected Activity Duration' ($t_e$) calculated from three-time estimates?",
         ["$t_e = \frac{a + 4m + b}{6}$ (where $a$ = Optimistic time, $m$ = Most likely time, $b$ = Pessimistic time)",
          "$t_e = \frac{a + m + b}{3}$",
          "$t_e = \frac{a + 2m + b}{4}$",
          "$t_e = b - a$"],
         0,
         "PERT uses a weighted Beta distribution formula: $t_e = \frac{a + 4m + b}{6}$, giving four times the weight to the most likely estimate ($m$)."),

        ("Project Management (CPM/PERT)",
         "In PERT, what is the formula for the variance of an activity's duration?",
         ["$\sigma^2 = \left(\frac{b - a}{6}\right)^2$",
          "$\sigma^2 = \frac{b - a}{36}$",
          "$\sigma^2 = \frac{b + a}{6}$",
          "$\sigma^2 = (b - a)^2$"],
         0,
         "Standard deviation $\sigma = \frac{b - a}{6}$, and variance $\sigma^2 = \left(\frac{b - a}{6}\right)^2$."),

        ("Project Management (CPM/PERT)",
         "What is 'Project Crashing' in CPM/PERT?",
         ["Accidentally deleting the project schedule database",
          "Shortening the overall project duration by allocating additional resources (e.g., overtime, extra labor, expedited shipping) to critical path activities at the lowest crash cost per unit time",
          "Terminating a project abruptly due to complete financial bankruptcy",
          "Physical damage caused to equipment during construction"],
         1,
         "Crashing reduces project time by spending extra funds on critical activities with the lowest Crash Cost per Period ($Crash\ Cost/Day = \frac{\Delta Cost}{\Delta Time}$)."),

        ("Project Management (CPM/PERT)",
         "What is a 'Work Breakdown Structure' (WBS)?",
         ["A physical demolition blueprint for tearing down older factory buildings",
          "A hierarchical decomposition of the total scope of work to be carried out by the project team to create the project deliverables and achieve project objectives",
          "A disciplinary record of employees who breakdown under work stress",
          "A list of broken factory tools awaiting repair"],
         1,
         "The WBS decomposes project scope into manageable, deliverable-oriented work packages, serving as the basis for scheduling, budgeting, and resource assignment."),

        # --- TOPIC 6: FORECASTING & SERVICE OPERATIONS (151-166) ---
        ("Forecasting & Service Operations",
         "In quantitative forecasting, what is the formula for 'Simple Exponential Smoothing'?",
         ["$F_{t+1} = F_t + \alpha (A_t - F_t)$ (where $F_{t+1}$ = new forecast, $F_t$ = previous forecast, $A_t$ = actual demand, $\alpha$ = smoothing constant)",
          "$F_{t+1} = \frac{A_t + A_{t-1} + A_{t-2}}{3}$",
          "$F_{t+1} = A_t \times \alpha$",
          "$F_{t+1} = F_t \times 2$"],
         0,
         "Exponential smoothing updates the prior forecast by adding a fraction ($\alpha$) of the most recent forecast error: $F_{t+1} = F_t + \alpha(A_t - F_t)$."),

        ("Forecasting & Service Operations",
         "If a forecaster sets the smoothing constant $\alpha = 1.0$ in exponential smoothing, what does the next forecast become?",
         ["The forecast becomes zero",
          "The next forecast equals the most recent actual demand exactly ($F_{t+1} = A_t$)",
          "The forecast equals the historical average of the last twenty years",
          "The forecast increases by 100% every period"],
         1,
         "When $\alpha = 1$, the formula reduces to $F_{t+1} = A_t$, meaning the model responds 100% to the latest actual demand (naive forecast)."),

        ("Forecasting & Service Operations",
         "What is 'MAD' (Mean Absolute Deviation) in forecasting error measurement?",
         ["The percentage of disgruntled customer feedback forms",
          "The average of the absolute values of the individual forecast errors: $MAD = \frac{\sum |A_t - F_t|}{n}$",
          "The maximum distance between factory delivery trucks",
          "The variance of corporate profit margins over five quarters"],
         1,
         "MAD measures average forecast error magnitude without considering direction: $MAD = \frac{\sum |Actual - Forecast|}{n}$."),

        ("Forecasting & Service Operations",
         "What is the 'Delphi Method' in qualitative forecasting?",
         ["An archaeological excavation technique used in Greece",
          "An iterative forecasting process using a panel of independent experts who answer anonymous questionnaires in rounds with summarized feedback until consensus is reached",
          "A mathematical linear programming equation solved by computers",
          "A customer survey conducted at shopping mall entrances"],
         1,
         "The Delphi Method aggregates expert judgments anonymously through iterative questionnaire rounds, eliminating interpersonal bias and dominant personalities."),

        ("Forecasting & Service Operations",
         "What are the four unique characteristics that distinguish 'Services' from 'Physical Manufactured Goods' (IHIP)?",
         ["Intangibility, Heterogeneity (Variability), Inseparability (Simultaneous production/consumption), and Perishability",
          "Inflation, Heavy weight, High price, and High risk",
          "Inspection, Hardness, Impermeability, and Plasticity",
          "Imported, Handcrafted, Industrial, and Packaged"],
         0,
         "Services are characterized by IHIP: Intangibility (no physical form), Heterogeneity (variable delivery), Inseparability (produced and consumed simultaneously), and Perishability (cannot be inventoried)."),

        ("Forecasting & Service Operations",
         "What is 'Service Blueprinting' in service design?",
         ["A physical architectural floor plan for constructing a customer service center",
          "A visual flowchart technique that maps customer journey touchpoints, front-stage visible actions, backstage invisible actions, and support processes separated by lines of visibility",
          "An engineering technical schematic for computer wiring",
          "A script read verbatim by call center operators"],
         1,
         "A Service Blueprint maps the end-to-end customer journey, separating visible frontstage customer touchpoints from backstage operational support systems via the Line of Visibility.")
    ]

    for i, (topic, q, opts, ans, exp) in enumerate(raw, 1):
        q_data.append({
            "id": f"MBA8111_{i:03d}",
            "courseCode": course_code,
            "courseTitle": course_title,
            "topic": topic,
            "question": q,
            "options": opts,
            "correctAnswer": ans,
            "explanation": exp
        })

    return q_data

if __name__ == "__main__":
    qs = get_questions()
    print(f"Generated {len(qs)} questions for MBA 8111.")
