# scripts/gen_mba8107.py
# 167 High-Yield MBA Questions for MBA 8107: Organisational Behaviour (OB)

def get_questions():
    course_code = "MBA 8107"
    course_title = "Organisational Behaviour"
    q_data = []

    raw = [
        # --- TOPIC 1: INDIVIDUAL BEHAVIOUR, PERSONALITY & PERCEPTION (1-25) ---
        ("Individual Behaviour & Personality",
         "The 'Big Five' (Five Factor Model - OCEAN) personality dimensions comprise:",
         ["Openness to Experience, Conscientiousness, Extraversion, Agreeableness, and Neuroticism (Emotional Stability)",
          "Optimism, Creativity, Efficiency, Authority, and Narcissism",
          "Organization, Competence, Empathy, Ambition, and Neutrality",
          "Orientation, Control, Expectancy, Aptitude, and Negotiation"],
         0,
         "The Big Five personality model includes Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism (or Emotional Stability)."),

        ("Individual Behaviour & Personality",
         "Which Big Five personality trait is consistently found to be the strongest predictor of overall job performance across diverse occupations?",
         ["Extraversion", "Conscientiousness", "Agreeableness", "Openness to Experience"],
         1,
         "Conscientiousness—reflecting dependability, organization, self-discipline, and goal-directed persistence—is the strongest cross-occupational predictor of job performance."),

        ("Individual Behaviour & Personality",
         "An individual with a strong 'Internal Locus of Control' believes that:",
         ["Outcomes in their life and career are primarily determined by luck, fate, powerful external forces, and chance",
          "Their own personal choices, effort, skills, and actions directly determine what happens to them",
          "Organizational politics is the sole determinant of career advancement",
          "Performance appraisals should be conducted strictly by external consultants"],
         1,
         "Internal locus of control is the belief that one controls one's own destiny; external locus attributes outcomes to environmental factors or luck (Rotter)."),

        ("Individual Behaviour & Personality",
         "In Myers-Briggs Type Indicator (MBTI) terminology, the dimension of 'Judging (J) vs. Perceiving (P)' describes how an individual:",
         ["Gathers and absorbs information from the external environment (Sensing vs. Intuition)",
          "Makes decisions and forms logical conclusions (Thinking vs. Feeling)",
          "Deals with and structures the outside world (preferring structured, organized closure vs. flexible, spontaneous adaptability)",
          "Directs their mental energy (Extraversion vs. Introversion)"],
         2,
         "Judging types prefer structure, planning, deadlines, and closure; Perceiving types prefer open-ended flexibility, spontaneity, and exploring options."),

        ("Individual Behaviour & Personality",
         "What is 'Machiavellianism' in organizational personality traits?",
         ["A personality characterized by high empathy, warm compassion, and selflessness",
          "A personality trait characterized by pragmatic, emotionally detached manipulation, political maneuvering, and the belief that 'the end justifies the means'",
          "A psychological syndrome causing extreme fear of public speaking",
          "A management style focused exclusively on artistic creativity"],
         1,
         "High Machs maintain emotional distance, manipulate interpersonal situations skillfully, and focus pragmatically on winning power and influence."),

        ("Individual Behaviour & Personality",
         "What is 'Type A Personality' characterized by in organizational settings?",
         ["A calm, relaxed, patient approach to deadlines with low competitiveness",
          "An aggressive involvement in a chronic, incessant struggle to achieve more and more in less and less time, accompanied by impatience, competitiveness, and urgency",
          "A complete lack of interest in professional career advancement",
          "A tendency to avoid all social interaction in workplace settings"],
         1,
         "Type A individuals exhibit intense competitiveness, time urgency, high work engagement, impatience, and higher susceptibility to stress-related ailments."),

        ("Individual Behaviour & Personality",
         "According to Harold Kelley's Attribution Theory, what three dimensions do people use to determine whether an observed behavior has an internal or external cause?",
         ["Distinctiveness, Consensus, and Consistency",
          "Direction, Intensity, and Persistence",
          "Diligence, Competence, and Integrity",
          "Dominance, Influence, and Compliance"],
         0,
         "Attribution Theory evaluates behavior across Consensus (do others act the same?), Distinctiveness (is this behavior unique to this task?), and Consistency (is this behavior regular over time?)."),

        ("Individual Behaviour & Personality",
         "What is the 'Fundamental Attribution Error'?",
         ["Attributing internal software glitches to computer hardware failures",
          "The tendency for observers to underestimate the impact of external situational factors and overestimate the influence of internal personal traits when judging others' behavior",
          "The mistake of assuming all employees have identical MBTI profiles",
          "Assuming that corporate profits are solely determined by tax rates"],
         1,
         "The fundamental attribution error leads people to blame others' mistakes on personality or character flaws rather than recognizing situational pressures."),

        ("Individual Behaviour & Personality",
         "What is 'Self-Serving Bias' in perceptual attribution?",
         ["A retail customer demanding a 50% cash discount at checkout",
          "The tendency for individuals to attribute their successes to internal factors (ability, effort) while blaming their failures on external factors (bad luck, difficult tasks, unfair bosses)",
          "An employee who cooks their own lunch in the office cafeteria",
          "A manager who delegates all presentation tasks to junior staff"],
         1,
         "Self-serving bias protects self-esteem by taking personal credit for triumphs while deflecting blame for setbacks onto environmental circumstances."),

        ("Individual Behaviour & Personality",
         "What is the 'Halo Effect' in perceptual appraisal?",
         ["A religious ceremony held in corporate meeting rooms",
          "A cognitive bias where an observer's general favorable impression of a person in one area (e.g., attractiveness or charisma) positively influences their overall judgment of their abilities in unrelated areas",
          "The illumination provided by modern LED office lighting fixtures",
          "A management practice of rewarding all employees identical bonus sums"],
         1,
         "The Halo Effect occurs when a single positive attribute paints an entire favorable evaluation (e.g., assuming an articulate employee must also be good at data analysis)."),

        ("Individual Behaviour & Personality",
         "What is 'Stereotyping' in social perception?",
         ["Operating industrial printing machinery in manufacturing plants",
          "Judging someone on the basis of one's perception of the demographic or social group to which that person belongs rather than their individual traits",
          "A technique used by audio recording engineers",
          "A mandatory corporate training class on typing speed"],
         1,
         "Stereotyping generalizes characteristics to an individual based on their membership in a racial, gender, age, or cultural group, overlooking personal variation."),

        ("Individual Behaviour & Personality",
         "What is 'Emotional Intelligence' (EQ/EI) as conceptualized by Daniel Goleman?",
         ["A measure of an individual's mathematical and spatial reasoning abilities",
          "The ability to recognize, understand, manage, and reason with our own emotions and the emotions of others, comprising self-awareness, self-regulation, motivation, empathy, and social skills",
          "The tendency to display intense emotional outbursts during boardroom debates",
          "A psychological assessment used exclusively for clinical therapy"],
         1,
         "Goleman's EQ framework consists of 5 core competencies: Self-Awareness, Self-Regulation, Internal Motivation, Empathy, and Social Skills."),

        ("Individual Behaviour & Personality",
         "In emotional labor theory (Arlie Hochschild), what is the difference between 'Surface Acting' and 'Deep Acting'?",
         ["Surface acting modifies displayed facial expressions/emotions without altering underlying feelings; Deep acting involves actively modifying internal feelings to genuinely experience the required emotion",
          "Surface acting takes place on theatrical stages; Deep acting takes place in cinema",
          "Surface acting is practiced by executives; Deep acting is practiced by interns",
          "Surface acting has zero emotional exhaustion; Deep acting is effortless"],
         0,
         "Surface acting (faking expressions) causes high emotional dissonance and burnout; deep acting aligns internal emotions with organizational display rules."),

        ("Individual Behaviour & Personality",
         "What is 'Cognitive Dissonance' (Leon Festinger)?",
         ["A severe hearing impairment caused by loud industrial machinery noise",
          "A state of psychological tension and discomfort experienced when an individual holds two contradictory beliefs, values, or when their actions clash with their attitudes",
          "An advanced neurological computing architecture used in AI",
          "A formal dispute between two competing marketing research firms"],
         1,
         "Cognitive dissonance arises from inconsistency between beliefs and behaviors, motivating individuals to change attitudes, justify behavior, or acquire new beliefs to restore consistency."),

        ("Individual Behaviour & Personality",
         "Which component of an attitude involves an individual's emotions, feelings, and affective evaluations toward an object or person?",
         ["Cognitive component", "Affective component", "Behavioral (Conative) component", "Structural component"],
         1,
         "Attitudes consist of the ABC triad: Affective (feelings/emotions), Behavioral (intention to act), and Cognitive (beliefs/knowledge)."),

        # --- TOPIC 2: MOTIVATION THEORIES & APPLICATIONS (26-60) ---
        ("Motivation Theories & Applications",
         "According to Abraham Maslow's Hierarchy of Needs, which need emerges at the very apex of the pyramid once all deficiency needs are met?",
         ["Physiological Needs", "Safety and Security Needs", "Social Belonging Needs", "Self-Actualization Needs"],
         3,
         "Self-Actualization—the drive to fulfill one's highest potential and achieve personal growth—sits at the apex of Maslow's hierarchy."),

        ("Motivation Theories & Applications",
         "In Frederick Herzberg's Two-Factor (Motivation-Hygiene) Theory, which of the following is categorized as a 'Hygiene Factor'?",
         ["Challenging work and personal achievement",
          "Recognition and career advancement",
          "Company policies, working conditions, base salary, and interpersonal supervision",
          "Opportunities for autonomy and professional responsibility"],
         2,
         "Hygiene factors (salary, supervision, company policy, physical work conditions) prevent job dissatisfaction when adequate, but do not create genuine motivation/satisfaction."),

        ("Motivation Theories & Applications",
         "According to Herzberg, true job satisfaction and high internal motivation are generated primarily by:",
         ["'Motivator Factors' such as achievement, recognition, meaningful responsibility, personal growth, and challenging work itself",
          "Providing free coffee and comfortable office chairs",
          "Increasing the frequency of executive board meetings",
          "Mandating strict 40-hour workweek punching clocks"],
         0,
         "Motivators are intrinsic to the content of the work (growth, responsibility, challenging tasks, accomplishment), fostering genuine long-term job satisfaction."),

        ("Motivation Theories & Applications",
         "Douglas McGregor's 'Theory X' assumes that employees:",
         ["Are naturally self-motivated, seek responsibility, and enjoy work as naturally as play",
          "Inherently dislike work, avoid responsibility whenever possible, and must be coerced, controlled, and threatened with punishment to achieve organizational goals",
          "Possess higher emotional intelligence than senior executive managers",
          "Require zero managerial supervision in autonomous teams"],
         1,
         "Theory X assumes workers are inherently lazy, self-centered, dislike work, and require autocratic oversight and carrot-and-stick controls."),

        ("Motivation Theories & Applications",
         "Douglas McGregor's 'Theory Y' posits that employees:",
         ["Must be micro-managed with continuous electronic surveillance",
          "Can view work as natural, exercise self-direction and self-control when committed to objectives, and actively seek creative problem-solving and responsibility",
          "Will only work if given daily cash wage disbursements",
          "Are incapable of learning complex analytical software"],
         1,
         "Theory Y holds an optimistic view: people are capable of self-direction, creativity, and intrinsic commitment when supportive environments are provided."),

        ("Motivation Theories & Applications",
         "David McClelland's Acquired Needs Theory identifies which three primary acquired human motives?",
         ["Need for Achievement (nAch), Need for Affiliation (nAff), and Need for Power (nPow)",
          "Need for Food, Need for Sleep, and Need for Shelter",
          "Need for Promotion, Need for Salary, and Need for Vacation",
          "Need for Control, Need for Autonomy, and Need for Compliance"],
         0,
         "McClelland's theory focuses on three learned social needs: nAch (mastery/excellence), nAff (warm social relationships), and nPow (influencing and directing others)."),

        ("Motivation Theories & Applications",
         "Victor Vroom's Expectancy Theory expresses motivational force through which multiplicative formula?",
         ["Motivation = Expectancy $\times$ Instrumentality $\times$ Valence ($M = E \times I \times V$)",
          "Motivation = Effort $+$ Salary $+$ Promotion",
          "Motivation = Ability $\times$ Education $\times$ Experience",
          "Motivation = Supervision $-$ Stress $+$ Bonus"],
         0,
         "Vroom's formula states: Expectancy (Effort $\rightarrow$ Performance probability) $\times$ Instrumentality (Performance $\rightarrow$ Outcome belief) $\times$ Valence (Value of the outcome). If any is zero, motivation is zero."),

        ("Motivation Theories & Applications",
         "In Vroom's Expectancy Theory, 'Instrumentality' is the belief that:",
         ["Exerting high effort will directly result in successful task performance",
          "Successful task performance will lead to receiving a specific desired organizational outcome or reward",
          "The organizational reward has positive personal emotional value to the individual",
          "The company's mechanical machines are operating at peak efficiency"],
         1,
         "Instrumentality is the subjective probability that achieving a given level of performance will actually be rewarded with the promised compensation or recognition."),

        ("Motivation Theories & Applications",
         "J. Stacy Adams' Equity Theory states that employees evaluate workplace fairness by:",
         ["Comparing their own ratio of job inputs (effort, skill, education) to job outcomes (pay, recognition) with the perceived input-outcome ratio of relevant comparison others",
          "Counting the total physical square footage of their cubicle desk",
          "Comparing their base salary directly to the CEO's stock options",
          "Measuring their daily typing speed against software benchmarks"],
         0,
         "Equity Theory shows that perceived inequity (under-reward or over-reward relative to referent others) creates psychological tension, prompting behavioral adjustments."),

        ("Motivation Theories & Applications",
         "According to Edwin Locke and Gary Latham's Goal-Setting Theory, motivation and task performance are highest when goals are:",
         ["Vague, generalized, and easy (e.g., 'Do your best')",
          "Specific, challenging (difficult but attainable), accepted, and accompanied by continuous constructive feedback",
          "Dictated autocratically without explaining the underlying strategic rationale",
          "Kept strictly secret from team members until project completion"],
         1,
         "Locke & Latham established that specific, challenging goals with feedback yield higher performance than easy or vague instructions like 'do your best'."),

        ("Motivation Theories & Applications",
         "In the Hackman & Oldham Job Characteristics Model (JCM), which five core job dimensions cultivate positive psychological states?",
         ["Skill Variety, Task Identity, Task Significance, Autonomy, and Job Feedback",
          "Salary, Supervision, Security, Status, and Seniority",
          "Speed, Strength, Stamina, Strategy, and Structure",
          "Software, Hardware, Bandwidth, Storage, and Memory"],
         0,
         "The JCM identifies 5 core job dimensions (Skill Variety, Task Identity, Task Significance, Autonomy, Feedback) that drive experienced meaningfulness, responsibility, and knowledge of results."),

        ("Motivation Theories & Applications",
         "What is 'Job Enrichment' as pioneered by Frederick Herzberg?",
         ["Adding more routine, repetitive tasks of the same nature to a job (Job Enlargement)",
          "Redesigning a job vertically to give the employee greater autonomy, responsibility, authority, and opportunities for personal and professional growth",
          "Increasing the base hourly wage of assembly workers by $1 per hour",
          "Rotating an employee between five different physical warehouse loading docks"],
         1,
         "Job enrichment vertically expands a role by incorporating planning, executing, and self-evaluating responsibilities, enhancing intrinsic motivation."),

        ("Motivation Theories & Applications",
         "What is 'Self-Determination Theory' (Deci & Ryan) focused on?",
         ["Financial wealth maximization through stock market trading",
          "The fundamental human needs for Autonomy (choice/volition), Competence (mastery/effectiveness), and Relatedness (connectedness/belonging) that fuel intrinsic motivation",
          "The legal right of sovereign nations to declare economic independence",
          "The calculation of corporate profit margins using econometric equations"],
         1,
         "Self-Determination Theory identifies Autonomy, Competence, and Relatedness as essential psychological nutriments for autonomous, self-sustained intrinsic motivation."),

        ("Motivation Theories & Applications",
         "What is the 'Overjustification Effect' in motivational psychology?",
         ["When managers write 50-page formal justifications for hiring new staff",
          "When introducing external tangible rewards (like cash) for an already intrinsically enjoyable activity diminishes the individual's intrinsic motivation to perform it",
          "When a company pays employees double their contractual wage rate",
          "When an employee works 80 hours a week without taking lunch breaks"],
         1,
         "The overjustification effect occurs when external incentives crowd out existing intrinsic interest, leading individuals to attribute their motivation purely to external rewards."),

        ("Motivation Theories & Applications",
         "What is 'Management by Objectives' (MBO) introduced by Peter Drucker?",
         ["A top-down autocratic decree specifying daily hourly production quotas",
          "A collaborative management process where managers and employees jointly set specific, measurable, time-bound objectives and periodically evaluate performance against those targets",
          "An accounting method used for tracking capital asset depreciation",
          "A legal framework for liquidating insolvent corporate subsidiaries"],
         1,
         "MBO aligns individual employee goals with enterprise strategic objectives through collaborative goal setting, objective progress tracking, and performance feedback."),

        # --- TOPIC 3: GROUP DYNAMICS, TEAMS & DECISION-MAKING (61-85) ---
        ("Group Dynamics & Teamwork",
         "Bruce Tuckman's model of team development identifies which sequential five stages?",
         ["Forming, Storming, Norming, Performing, and Adjourning",
          "Conceiving, Budgeting, Implementing, Auditing, and Liquidating",
          "Recruiting, Training, Disciplining, Promoting, and Retiring",
          "Planning, Organizing, Leading, Controlling, and Reviewing"],
         0,
         "Tuckman's 5 stages trace group evolution: Forming (orientation), Storming (conflict/jockeying), Norming (cohesion/rules), Performing (synergy/execution), and Adjourning (dissolution)."),

        ("Group Dynamics & Teamwork",
         "During which stage of Tuckman's model do team members typically experience interpersonal friction, power struggles, and disagreements over roles and leadership?",
         ["Forming", "Storming", "Norming", "Performing"],
         1,
         "Storming involves interpersonal friction, competition for status, and role conflicts as members negotiate boundaries before establishing group norms."),

        ("Group Dynamics & Teamwork",
         "What is 'Groupthink' as formulated by Irving Janis?",
         ["A highly effective collaborative brainstorming session that generates hundreds of creative innovations",
          "A mode of thinking that occurs when the desire for harmony, cohesion, and conformity in a decision-making group overrides realistic appraisal of alternatives, leading to flawed decisions",
          "A computer network connecting multiple mainframe processors",
          "A formal cognitive psychology exam administered to team managers"],
         1,
         "Groupthink is a dysfunctional consensus-seeking bias characterized by self-censorship, illusion of invulnerability, and pressure on dissenters (e.g., Bay of Pigs, Challenger disaster)."),

        ("Group Dynamics & Teamwork",
         "What is 'Social Loafing' (the Ringelmann Effect) in group performance?",
         ["Taking scheduled lunch breaks with colleagues in the corporate cafeteria",
          "The tendency for individuals to exert less physical or cognitive effort when working collectively in a group than when working individually and held individually accountable",
          "A relaxing team-building weekend retreat hosted at a beach resort",
          "An employee who actively mentors junior apprentices during work hours"],
         1,
         "Social loafing occurs when individual contributions are pooled and not individually identifiable, reducing perceived responsibility and personal effort."),

        ("Group Dynamics & Teamwork",
         "What is 'Group Polarization' (or Groupshift)?",
         ["When team members physically sit on opposite sides of the conference table",
          "The tendency for group discussion to intensify and shift the group's collective decision toward a more extreme position (either much riskier or much more cautious) than the initial individual preferences",
          "A total breakdown of communication resulting in immediate team dissolution",
          "A legal dispute between two rival trade union factions"],
         1,
         "Group polarization occurs when deliberations reinforce and exaggerate pre-existing attitudes, leading to riskier or more extreme collective decisions than individuals would make alone."),

        ("Group Dynamics & Teamwork",
         "In Meredith Belbin's Team Roles framework, the 'Plant' role is characterized as:",
         ["The individual who waters the indoor office houseplants",
          "An individual who is highly creative, imaginative, unconventional, and a natural generator of unorthodox ideas and solutions to complex problems",
          "The strict disciplinarian who enforces punctual meeting attendance",
          "The corporate legal counsel who reviews vendor contracts"],
         1,
         "In Belbin's model, the 'Plant' is the innovative, creative intellect who proposes original, out-of-the-box ideas to solve tough problems."),

        ("Group Dynamics & Teamwork",
         "What is the 'Nominal Group Technique' (NGT) in group decision-making?",
         ["A casual group conversation with zero agenda or formal facilitator",
          "A structured method where participants independently generate ideas in writing, share them in round-robin fashion, discuss for clarity, and vote/rank silently to reach a decision",
          "A voting system where only senior executive directors are permitted to vote",
          "An automated software algorithm that generates randomized slogans"],
         1,
         "NGT restricts verbal discussion during initial ideation to prevent dominant personalities from hijacking the session, using silent generation and pooled ranking."),

        ("Group Dynamics & Teamwork",
         "What is 'Psychological Safety' in teams as researched by Amy Edmondson (and Google's Project Aristotle)?",
         ["Installing bulletproof glass and security guards around office meeting rooms",
          "A shared belief held by team members that the team is safe for interpersonal risk-taking, speaking up with ideas, asking questions, and admitting mistakes without fear of humiliation or punishment",
          "Providing mandatory health insurance coverage to all employees",
          "An assessment of building fire safety and emergency exit routes"],
         1,
         "Psychological safety is the bedrock of high-performing teams, allowing members to voice vulnerabilities, suggest wild ideas, and challenge assumptions safely."),

        ("Group Dynamics & Teamwork",
         "In team structure design, what is a 'Cross-Functional Team'?",
         ["A team composed of employees who are cross-trained in athletics",
          "A group of individuals with diverse functional expertise (e.g., Engineering, Marketing, Finance, Operations) working together toward a common goal or project",
          "A team where members rotate managers every calendar week",
          "A team formed exclusively by external management consultants"],
         1,
         "Cross-functional teams bring together specialists from different departments to break down silos, accelerate innovation, and deliver complex integrated products."),

        ("Group Dynamics & Teamwork",
         "What is 'Role Ambiguity' in organizational behaviour?",
         ["When an actor forgets their lines in a corporate theatrical video",
          "A condition where an employee lacks clear, definitive information about their job responsibilities, expectations, scope of authority, and performance evaluation criteria",
          "A situation where two employees share the exact same job title",
          "A corporate policy allowing employees to wear casual attire on Fridays"],
         1,
         "Role ambiguity occurs when job duties and performance expectations are unclear, causing employee anxiety, stress, and lowered productivity."),

        # --- TOPIC 4: LEADERSHIP THEORIES & POWER DYNAMICS (86-125) ---
        ("Leadership Theories & Power",
         "In Blake and Mouton's Managerial Grid, which leadership style represents the optimal 'Team Management' (9,9) style?",
         ["High concern for production (9) and low concern for people (1) - Authority-Compliance",
          "High concern for people (9) and low concern for production (1) - Country Club",
          "Low concern for production (1) and low concern for people (1) - Impoverished",
          "High concern for both production (9) and people (9) - Team Management"],
         3,
         "The 9,9 Team Management style integrates high dedication to operational excellence and productivity with deep commitment to employee trust, empowerment, and welfare."),

        ("Leadership Theories & Power",
         "Fred Fiedler's Contingency Model of leadership posits that effective group performance depends upon:",
         ["The leader's genetic ancestry and biological physical height",
          "The proper match between the leader's fixed personality style (task-oriented vs. relationship-oriented, measured by LPC) and the degree of situational control/favorableness",
          "How much money the leader invests in annual advertising campaigns",
          "The speed at which the leader makes unilateral decisions without consulting staff"],
         1,
         "Fiedler's LPC model argues that leadership style is fixed; leaders succeed by being matched to situations (Leader-Member Relations, Task Structure, Position Power) that fit their style."),

        ("Leadership Theories & Power",
         "In Hersey and Blanchard's Situational Leadership Theory (SLT), what leadership style is recommended for followers who have 'Low Competence but High Commitment' (Enthusiastic Beginner)?",
         ["Directing / Telling (High Task, Low Relationship)",
          "Coaching / Selling (High Task, High Relationship)",
          "Supporting / Participating (Low Task, High Relationship)",
          "Delegating (Low Task, Low Relationship)"],
         0,
         "For enthusiastic beginners with low skill but high eagerness, leaders should use a Directing/Telling style, providing clear, step-by-step guidance and close supervision."),

        ("Leadership Theories & Power",
         "Robert House's Path-Goal Theory states that the primary role of a leader is to:",
         ["Dictate 100% of employee personal opinions and lifestyle choices",
          "Clarify the paths to goals, remove roadblocks and obstacles, and provide appropriate support to help subordinates achieve both personal and organizational objectives",
          "Construct physical paved walkways across corporate office parks",
          "Maximize the number of disciplinary memos issued per quarter"],
         1,
         "Path-Goal theory (rooted in Expectancy theory) emphasizes that leaders must adapt behavior (directive, supportive, participative, achievement-oriented) to help followers reach goals."),

        ("Leadership Theories & Power",
         "According to Bernard Bass, what are the 'Four Is' of Transformational Leadership?",
         ["Idealized Influence (Charisma), Inspirational Motivation, Intellectual Stimulation, and Individualized Consideration",
          "Inspection, Intervention, Intimidation, and Isolation",
          "Information, Implementation, Infrastructure, and Investment",
          "Ideation, Iteration, Integration, and Institutionalization"],
         0,
         "The 4 Is of Transformational Leadership are Idealized Influence (role modeling), Inspirational Motivation (vision), Intellectual Stimulation (innovation), and Individualized Consideration (coaching)."),

        ("Leadership Theories & Power",
         "How does 'Transactional Leadership' differ fundamentally from 'Transformational Leadership'?",
         ["Transactional leadership relies on exchange relationships, contingent rewards, and management-by-exception to maintain performance; Transformational leadership inspires followers to transcend self-interest for a shared vision and change",
          "Transactional leadership is illegal in stock-listed corporations; Transformational is mandatory",
          "Transactional leaders work only in retail banking; Transformational leaders work in software",
          "Transactional leadership uses zero communication; Transformational leadership uses only email"],
         0,
         "Transactional leadership focuses on contracts, monitoring, and contingent rewards ($quid\ pro\ quo$), while transformational leadership drives change, vision, and intrinsic motivation."),

        ("Leadership Theories & Power",
         "In Robert Greenleaf's 'Servant Leadership' philosophy, the leader's primary priority is to:",
         ["Accumulate personal power, status, and luxury corporate perks",
          "Serve the needs of followers, help them develop and perform at their highest capacity, and prioritize the growth and well-being of people and communities",
          "Ensure that employees serve the executive board with unquestioning obedience",
          "Maximize short-term quarterly cash dividend yields for institutional funds"],
         1,
         "Servant leadership flips the traditional hierarchy: the leader serves first, empowering, developing, and supporting team members to flourish."),

        ("Leadership Theories & Power",
         "What is 'Leader-Member Exchange' (LMX) Theory?",
         ["A currency exchange booth operated inside corporate office lobbies",
          "A theory focusing on the two-way relationship between leaders and followers, showing that leaders form high-trust, high-quality exchanges with an 'In-Group' and formal transactional exchanges with an 'Out-Group'",
          "A rotation program where managers and employees swap jobs every month",
          "A mandatory performance appraisal conducted by labor unions"],
         1,
         "LMX theory demonstrates that leaders develop differentiated relationships with subordinates; high LMX ('in-group') followers receive greater trust, autonomy, and career support."),

        ("Leadership Theories & Power",
         "According to John French and Bertram Raven, which base of power stems from an individual's possession of specialized knowledge, unique technical expertise, or valuable skills?",
         ["Legitimate Power", "Reward Power", "Coercive Power", "Expert Power"],
         3,
         "Expert power derives from possessing specialized knowledge, advanced credentials, technical competence, or unique expertise that others depend upon."),

        ("Leadership Theories & Power",
         "What is 'Referent Power' in French and Raven's power taxonomy?",
         ["Power derived from the formal organizational hierarchy and official job title",
          "Power based on identification with, admiration for, and personal respect of a leader because of their charisma, integrity, and character",
          "Power based on the ability to inflict disciplinary penalties and firing",
          "Power based on having a large number of academic bibliography references"],
         1,
         "Referent power is interpersonal influence rooted in charisma, personal magnetism, and the desire of others to emulate and follow the leader."),

        ("Leadership Theories & Power",
         "What is 'Coercive Power'?",
         ["The capacity to reward employees with monetary bonuses and promotions",
          "The ability to influence others through fear of punishment, withholding of rewards, demotion, termination, or official reprimands",
          "Influence gained through gentle persuasive logical reasoning",
          "Power established through unanimous democratic employee elections"],
         1,
         "Coercive power relies on fear, threats, disciplinary sanctions, or negative consequences to compel compliance, often leading to resistance and resentment."),

        ("Leadership Theories & Power",
         "What is 'Impression Management' in organizational politics?",
         ["The physical printing of business cards on heavy cardstock",
          "The deliberate process by which individuals attempt to control, shape, and influence the perceptions and impressions that other people form of them in the workplace",
          "A graphic design technique used for product brochures",
          "A formal performance appraisal metric used by HR"],
         1,
         "Impression management utilizes self-promotion, ingratiation, exemplification, and strategic framing to cultivate a desired professional image."),

        # --- TOPIC 5: COMMUNICATION, CONFLICT & NEGOTIATION (126-145) ---
        ("Communication, Conflict & Negotiation",
         "In the Shannon-Weaver communication model, what represents any interference, distraction, or distortion that hinders the accurate transmission and decoding of a message?",
         ["Encoder", "Channel", "Noise", "Feedback"],
         2,
         "Noise is any internal (bias, stress) or external (static, ambient sound, distraction) barrier that distorts or interferes with message transmission and reception."),

        ("Communication, Conflict & Negotiation",
         "What is the 'Grapevine' in organizational communication?",
         ["A physical vineyard planted outside corporate cafeterias",
          "The informal, unofficial, word-of-mouth communication network that operates across all levels of an organization outside formal channels",
          "A secure encrypted email messaging system used by executive directors",
          "A weekly printed company newsletter mailed to retirees"],
         1,
         "The grapevine is the informal network of social communication in organizations, rapidly transmitting rumors, news, and workplace sentiment."),

        ("Communication, Conflict & Negotiation",
         "What are the five conflict-handling modes identified in the Thomas-Kilmann Conflict Mode Instrument (TKM)?",
         ["Competing, Collaborating, Compromising, Avoiding, and Accommodating",
          "Attacking, Defending, Retaliating, Escaping, and Surrendering",
          "Planning, Organizing, Leading, Controlling, and Executing",
          "Ignoring, Denying, Litigating, Arbitrating, and Liquidating"],
         0,
         "The Thomas-Kilmann framework maps conflict styles across Assertiveness (satisfying own concerns) and Cooperativeness (satisfying others' concerns): Competing, Collaborating, Compromising, Avoiding, Accommodating."),

        ("Communication, Conflict & Negotiation",
         "In the Thomas-Kilmann model, which conflict style is characterized as high in assertiveness and high in cooperativeness, seeking an integrative 'Win-Win' solution?",
         ["Competing", "Collaborating", "Avoiding", "Accommodating"],
         1,
         "Collaborating works creatively to find a win-win solution that fully satisfies the underlying concerns and vital interests of both parties."),

        ("Communication, Conflict & Negotiation",
         "What does 'BATNA' stand for in negotiation theory (Fisher & Ury, *Getting to Yes*)?",
         ["Best Alternative To a Negotiated Agreement",
          "Basic Assessment of Tactical Negotiation Assets",
          "Board Approved Total Net Allocation",
          "Bilateral Agreement for Tariff Neutral Action"],
         0,
         "BATNA is the most advantageous alternative course of action a party can take if negotiations reach an impasse, representing one's walkaway leverage."),

        ("Communication, Conflict & Negotiation",
         "What is the difference between 'Distributive Bargaining' and 'Integrative Bargaining'?",
         ["Distributive bargaining is a zero-sum, fixed-pie negotiation ('Win-Lose'); Integrative bargaining expands the pie to create mutual value ('Win-Win')",
          "Distributive bargaining is used only in agriculture; Integrative is used in software",
          "Distributive bargaining requires five lawyers; Integrative requires none",
          "Distributive bargaining is illegal under trade law; Integrative is mandatory"],
         0,
         "Distributive bargaining divides a fixed amount of resources (competitive, adversarial); integrative bargaining searches for collaborative synergies to maximize collective value."),

        ("Communication, Conflict & Negotiation",
         "What is the 'Zone of Possible Agreement' (ZOPA) in negotiation?",
         ["A demilitarized border zone established by the United Nations",
          "The overlapping range between the buyer's maximum willingness to pay (reservation price) and the seller's minimum acceptable price (reservation price) where an agreement can be reached",
          "A designated quiet room inside corporate conference facilities",
          "The total geographical area covered by a sales territory"],
         1,
         "ZOPA is the bargaining range between the reservation points of both parties; if reservation prices overlap, a mutually beneficial deal is mathematically possible."),

        # --- TOPIC 6: ORGANIZATIONAL CULTURE, CHANGE & STRESS (146-167) ---
        ("Organizational Culture, Change & Stress",
         "According to Edgar Schein, what are the three levels of Organizational Culture, ordered from the most visible to the deepest and least visible?",
         ["Artifacts, Espoused Values, and Basic Underlying Assumptions",
          "Policies, Procedures, and Penalties",
          "Logos, Slogans, and Commercials",
          "Salaries, Bonuses, and Stock Options"],
         0,
         "Schein's 3 levels: Surface Artifacts (dress code, office layout) $\rightarrow$ Espoused Values (stated philosophies/goals) $\rightarrow$ Basic Underlying Assumptions (deeply ingrained, unconscious beliefs)."),

        ("Organizational Culture, Change & Stress",
         "What are 'Basic Underlying Assumptions' in Schein's model of organizational culture?",
         ["The annual financial budget assumptions approved by accountants",
          "Unconscious, taken-for-granted, deeply embedded beliefs, perceptions, and values that guide member behavior and determine how they perceive and feel about reality",
          "The written employee code of conduct handbook given to new hires",
          "The architectural structural blueprints of company buildings"],
         1,
         "Basic underlying assumptions are the deepest, invisible core of culture—implicit assumptions about human nature, environment, and relationships that are rarely debated."),

        ("Organizational Culture, Change & Stress",
         "In the Competing Values Framework (Cameron & Quinn), which organizational culture type emphasizes internal focus, flexibility, teamwork, participation, and a family-like atmosphere?",
         ["Hierarchy Culture", "Market Culture", "Clan Culture", "Adhocracy Culture"],
         2,
         "Clan culture prioritizes internal cohesion, collaboration, employee development, empowerment, and a nurturing, family-like work environment."),

        ("Organizational Culture, Change & Stress",
         "Which culture in the Competing Values Framework focuses externally on flexibility, dynamic innovation, entrepreneurship, and risk-taking?",
         ["Adhocracy Culture", "Hierarchy Culture", "Clan Culture", "Market Culture"],
         0,
         "Adhocracy culture thrives on agility, cutting-edge innovation, risk-taking, and rapid adaptation to dynamic external opportunities (e.g., tech startups)."),

        ("Organizational Culture, Change & Stress",
         "Kurt Lewin's classic Three-Step Change Model progresses through which phases?",
         ["Unfreezing, Changing (Moving), and Refreezing",
          "Planning, Budgeting, and Auditing",
          "Conceiving, Executing, and Liquidating",
          "Restructuring, Downsizing, and Outsourcing"],
         0,
         "Lewin's 3-step model: Unfreezing (breaking equilibrium, creating readiness) $\rightarrow$ Changing (implementing new processes/behaviors) $\rightarrow$ Refreezing (reinforcing and institutionalizing changes)."),

        ("Organizational Culture, Change & Stress",
         "What is 'Force Field Analysis' introduced by Kurt Lewin?",
         ["A physics experiment measuring magnetic fields around computers",
          "A diagnostic tool that analyzes the balance between 'Driving Forces' (forces pushing for change) and 'Restraining Forces' (forces resisting change)",
          "A military tactical assessment used for security perimeter planning",
          "An evaluation of gravitational pull on factory equipment"],
         1,
         "Force Field Analysis identifies driving forces that promote change and restraining forces that inhibit change, helping leaders design interventions to shift the equilibrium."),

        ("Organizational Culture, Change & Stress",
         "John Kotter's 8-Step Change Model begins with which crucial first step?",
         ["Consolidating gains and producing more change",
          "Creating a sense of urgency around a critical business need or opportunity",
          "Empowering broad-based action by removing obstacles",
          "Anchor new approaches in the corporate culture"],
         1,
         "Step 1 in Kotter's 8-step framework is 'Create a Sense of Urgency' by highlighting competitive threats or compelling opportunities to overcome organizational complacency."),

        ("Organizational Culture, Change & Stress",
         "What is the primary reason why organizational change initiatives encounter intense employee resistance?",
         ["Employees inherently enjoy attending software training classes",
          "Fear of the unknown, perceived loss of status/power, economic insecurity, habit disruption, and lack of trust in leadership communication",
          "Employees wanting to work longer overtime hours",
          "Excessive corporate cash bonus distributions"],
         1,
         "Resistance to change is driven by psychological fear of loss (control, competence, income, relationships), uncertainty, and disruption of established habits."),

        ("Organizational Culture, Change & Stress",
         "What is 'Burnout' in occupational psychology?",
         ["A physical electrical fire occurring inside office servers",
          "A syndrome of chronic workplace stress that has not been successfully managed, characterized by emotional exhaustion, depersonalization/cynicism, and reduced personal accomplishment",
          "A scheduled corporate fireworks celebration for annual holidays",
          "An employee retiring after 40 years of service with full pension benefits"],
         1,
         "As recognized by the WHO, burnout is an occupational phenomenon manifesting as emotional exhaustion, cynicism/mental distance from work, and feelings of inefficacy."),

        ("Organizational Culture, Change & Stress",
         "What is 'Eustress' versus 'Distress' in stress management?",
         ["Eustress is positive, motivating stress that enhances performance and focus; Distress is negative, overwhelming stress that impairs cognitive and physical functioning",
          "Eustress occurs in European countries; Distress occurs in Asian countries",
          "Eustress is experienced by managers; Distress is experienced by interns",
          "There is zero difference; all stress is inherently destructive"],
         0,
         "Eustress is constructive, optimal stress that stimulates alertness and peak performance (Yerkes-Dodson Law); Distress is excessive, debilitating strain."),

        ("Organizational Culture, Change & Stress",
         "What is the 'Yerkes-Dodson Law' regarding stress and job performance?",
         ["Performance increases linearly with stress to infinity",
          "There is an inverted U-shaped relationship where performance peaks at moderate levels of arousal/stress and drops off when stress is too low or too high",
          "Zero stress guarantees the highest possible intellectual productivity",
          "Stress has no measurable relationship with work output"],
         1,
         "The Yerkes-Dodson law shows that moderate arousal/stress optimizes focus and productivity; too little causes boredom, while excessive strain causes anxiety and collapse.")
    ]

    for i, (topic, q, opts, ans, exp) in enumerate(raw, 1):
        q_data.append({
            "id": f"MBA8107_{i:03d}",
            "courseCode": course_code,
            "courseTitle": course_title,
            "topic": topic,
            "question": q,
            "options": opts,
            "correctAnswer": ans,
            "explanation": exp
        })

    return q_data

if __name__ == "__main__":
    qs = get_questions()
    print(f"Generated {len(qs)} questions for MBA 8107.")
